namespace OfficeEditor.Api.Services;

public sealed class SampleFileService : ISampleFileService
{
    private static readonly IReadOnlyList<SampleFile> SampleFiles = new List<SampleFile>
    {
        new(
            "sales_acceleration_deck.pptx",
            "examples/REF/PPTX/sales_acceleration_deck.pptx",
            OfficeEditor.Core.Services.OfficeDocumentFormat.Pptx,
            "The primary license-clean 16-slide sales REF deck with 5 diagram parts."),
        new(
            "northwind-demo.pptx",
            "examples/REF/PPTX/northwind-demo.pptx",
            OfficeEditor.Core.Services.OfficeDocumentFormat.Pptx,
            "A self-made 15-slide Northwind Labs demo deck (generated by OfficeEditor)."),
        new(
            "annual-report.docx",
            "examples/REF/DOCX/annual-report.docx",
            OfficeEditor.Core.Services.OfficeDocumentFormat.Docx,
            "A license-clean annual-report DOCX (python-docx authored, Word-rendered PDF)."),
        new(
            "monitoring-report.docx",
            "examples/REF/DOCX/monitoring-report.docx",
            OfficeEditor.Core.Services.OfficeDocumentFormat.Docx,
            "A license-clean monitoring-report DOCX (python-docx authored, Word-rendered PDF)."),
        new(
            "sample.md",
            "examples/Docx/sample.md",
            OfficeEditor.Core.Services.OfficeDocumentFormat.Markdown,
            "A Markdown sample used to test Markdown-to-DOCX conversion.")
    };

    public IReadOnlyList<SampleFile> GetSampleFiles() => SampleFiles;

    public async Task<byte[]> LoadAsync(string name, CancellationToken ct = default)
    {
        var sample = SampleFiles.FirstOrDefault(s => s.Name == name)
            ?? throw new FileNotFoundException($"Sample file '{name}' was not found.");

        var repoRoot = RepositoryRootLocator.FindOrFallback();
        var fullPath = Path.GetFullPath(Path.Combine(repoRoot, sample.Path.Replace('/', Path.DirectorySeparatorChar)));

        if (!File.Exists(fullPath))
        {
            throw new FileNotFoundException($"Sample file not found on disk: {fullPath}");
        }

        return await File.ReadAllBytesAsync(fullPath, ct).ConfigureAwait(false);
    }
}

public interface ISampleFileService
{
    IReadOnlyList<SampleFile> GetSampleFiles();
    Task<byte[]> LoadAsync(string name, CancellationToken ct = default);
}

public record SampleFile(string Name, string Path, OfficeEditor.Core.Services.OfficeDocumentFormat Format, string Description);
