using System.Globalization;

namespace PptxEditor.Core.Converters.SmartArt;

/// <summary>
/// Evaluates ECMA-376 preset-geometry definitions (guide formulas + path commands)
/// for the SmartArt presets whose faithful outline requires per-shape math:
/// <c>gear6</c>, <c>gear9</c>, <c>circularArrow</c>, <c>leftCircularArrow</c>,
/// <c>blockArc</c> (elliptical arcs, flattened to polylines in ~2° steps) and
/// <c>homePlate</c>, <c>flowChartManualOperation</c>, <c>quadArrow</c> (pure
/// polygons whose vertices depend on the shape aspect ratio and a:avLst
/// adjustments). Definitions are transcribed from the ECMA-376 preset geometry
/// definitions (the same source as LibreOffice's presetShapeDefinitions.xml) and
/// honor each shape's <c>a:avLst</c> adjustment values; returned points are
/// normalized to 0..1 of the shape extent.
/// </summary>
internal static class SmartArtPresetGeometry
{
    /// <summary>OOXML angles are expressed in 60000ths of a degree.</summary>
    private const double AngleToRadians = Math.PI / (180.0 * 60000.0);

    /// <summary>Arc flattening step: 2° in OOXML angle units.</summary>
    private const double ArcStepAngle = 2.0 * 60000.0;

    internal sealed record PresetDef(
        IReadOnlyDictionary<string, double> Defaults,
        IReadOnlyList<string> Guides,
        IReadOnlyList<string> Path);

    /// <summary>
    /// Builds the normalized (0..1) outline points for <paramref name="prst"/> at
    /// shape size <paramref name="w"/>×<paramref name="h"/> (only the aspect ratio
    /// matters), honoring the given adjustment values. Returns null when the preset
    /// is not one of the arc-based presets handled here — the caller then falls
    /// back to its static polygon table.
    /// </summary>
    internal static List<(double X, double Y)>? TryBuildNormalizedPoints(
        string prst, double w, double h, IReadOnlyDictionary<string, double> adjustments)
    {
        if (!Presets.TryGetValue(prst, out var def) || w <= 0 || h <= 0)
            return null;

        var env = new Dictionary<string, double>(StringComparer.Ordinal)
        {
            ["w"] = w, ["h"] = h, ["ss"] = Math.Min(w, h),
            ["hd2"] = h / 2, ["wd2"] = w / 2, ["hc"] = w / 2, ["vc"] = h / 2,
            ["l"] = 0, ["t"] = 0, ["r"] = w, ["b"] = h,
            ["cd2"] = 10800000, ["cd4"] = 5400000, ["cd8"] = 2700000,
            ["3cd4"] = 16200000, ["3cd8"] = 8100000, ["5cd8"] = 13500000, ["7cd8"] = 18900000,
        };
        foreach (var (name, value) in def.Defaults)
            env[name] = value;
        foreach (var (name, value) in adjustments)
            env[name] = value;

        // Guides are evaluated in document order into the shared environment;
        // a redefined name (e.g. gear6's second "a1") simply overwrites.
        foreach (var guide in def.Guides)
        {
            var separator = guide.IndexOf(' ');
            env[guide[..separator]] = Evaluate(env, guide[(separator + 1)..]);
        }

        var points = FlattenPath(env, def.Path, w, h);

        // Degenerate adjustment combinations can yield non-finite coordinates
        // (e.g. sqrt of a negative intermediate); such a shape is unrenderable.
        return points.Any(p => !double.IsFinite(p.X) || !double.IsFinite(p.Y)) ? null : points;
    }

    private static List<(double X, double Y)> FlattenPath(
        Dictionary<string, double> env, IReadOnlyList<string> path, double w, double h)
    {
        var points = new List<(double X, double Y)>();
        double curX = 0, curY = 0;

        foreach (var command in path)
        {
            var tokens = command.Split(' ');
            switch (tokens[0])
            {
                case "M":
                case "L":
                    curX = Value(env, tokens[1]);
                    curY = Value(env, tokens[2]);
                    points.Add((curX / w, curY / h));
                    break;
                case "A":
                {
                    // ECMA-376 arcTo: the arc lies on the ellipse with radii
                    // (wR, hR); the center is implied by the current pen point
                    // sitting at stAng on that ellipse. Sweep runs from stAng by
                    // swAng (negative = counterclockwise).
                    var wR = Value(env, tokens[1]);
                    var hR = Value(env, tokens[2]);
                    var stAng = Value(env, tokens[3]);
                    var swAng = Value(env, tokens[4]);
                    var cx = curX - wR * Math.Cos(stAng * AngleToRadians);
                    var cy = curY - hR * Math.Sin(stAng * AngleToRadians);
                    var steps = Math.Max(2, (int)Math.Ceiling(Math.Abs(swAng) / ArcStepAngle));
                    for (var i = 1; i <= steps; i++)
                    {
                        var angle = (stAng + swAng * i / steps) * AngleToRadians;
                        curX = cx + wR * Math.Cos(angle);
                        curY = cy + hR * Math.Sin(angle);
                        points.Add((curX / w, curY / h));
                    }
                    break;
                }
                case "Z":
                    break;
                default:
                    throw new InvalidOperationException($"Unknown preset path command '{command}'.");
            }
        }

        return points;
    }

    private static double Evaluate(Dictionary<string, double> env, string formula)
    {
        var tokens = formula.Split(' ');
        double Arg(int index) => Value(env, tokens[index + 1]);
        return tokens[0] switch
        {
            "val" => Arg(0),
            "+-" => Arg(0) + Arg(1) - Arg(2),
            "+/" => (Arg(0) + Arg(1)) / Arg(2),
            "*/" => Arg(0) * Arg(1) / Arg(2),
            "pin" => Math.Clamp(Arg(1), Arg(0), Arg(2)),
            "mod" => Math.Sqrt(Arg(0) * Arg(0) + Arg(1) * Arg(1) + Arg(2) * Arg(2)),
            "at2" => Math.Atan2(Arg(1), Arg(0)) / AngleToRadians,
            "cos" => Arg(0) * Math.Cos(Arg(1) * AngleToRadians),
            "sin" => Arg(0) * Math.Sin(Arg(1) * AngleToRadians),
            "cat2" => Arg(0) * Math.Cos(Math.Atan2(Arg(2), Arg(1))),
            "sat2" => Arg(0) * Math.Sin(Math.Atan2(Arg(2), Arg(1))),
            "sqrt" => Math.Sqrt(Arg(0)),
            "abs" => Math.Abs(Arg(0)),
            "min" => Math.Min(Arg(0), Arg(1)),
            "max" => Math.Max(Arg(0), Arg(1)),
            "?:" => Arg(0) > 0 ? Arg(1) : Arg(2),
            var op => throw new InvalidOperationException($"Unknown preset guide operator '{op}'.")
        };
    }

    private static double Value(Dictionary<string, double> env, string token)
    {
        if (double.TryParse(token, NumberStyles.Float, CultureInfo.InvariantCulture, out var literal))
            return literal;
        if (env.TryGetValue(token, out var value))
            return value;
        throw new InvalidOperationException($"Unknown preset guide reference '{token}'.");
    }

    private static readonly IReadOnlyDictionary<string, PresetDef> Presets =
        new Dictionary<string, PresetDef>(StringComparer.Ordinal)
    {
        // ECMA-376: point depth dx1 = ss·a/100000 with a = pin(0, adj, 100000·w/ss)
        // — the depth is a fraction of min(w,h), so it MUST be computed per shape.
        ["homePlate"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj"] = 50000,
            },
            new[]
            {
                "maxAdj */ 100000 w ss",
                "a pin 0 adj maxAdj",
                "dx1 */ ss a 100000",
                "x1 +- r 0 dx1",
            },
            new[]
            {
                "M l t",
                "L x1 t",
                "L r vc",
                "L x1 b",
                "L l b",
                "Z",
            }),

        // ECMA-376 flowChartManualOperation has no avLst: a fixed path in 5x5
        // space — full-width top edge, bottom edge inset by w/5 on both sides.
        ["flowChartManualOperation"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>(),
            new[]
            {
                "x1 */ w 1 5",
                "x2 */ w 4 5",
            },
            new[]
            {
                "M l t",
                "L r t",
                "L x2 b",
                "L x1 b",
                "Z",
            }),

        // ECMA-376 quadArrow: adj1 = shaft thickness, adj2 = head half-width,
        // adj3 = head length (all fractions of ss). 24-vertex cross of 4 arrows.
        ["quadArrow"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 22500,
                ["adj2"] = 22500,
                ["adj3"] = 22500,
            },
            new[]
            {
                "a2 pin 0 adj2 50000",
                "maxAdj1 */ a2 2 1",
                "a1 pin 0 adj1 maxAdj1",
                "q1 +- 100000 0 maxAdj1",
                "maxAdj3 */ q1 1 2",
                "a3 pin 0 adj3 maxAdj3",
                "x1 */ ss a3 100000",
                "dx2 */ ss a2 100000",
                "x2 +- hc 0 dx2",
                "x5 +- hc dx2 0",
                "dx3 */ ss a1 200000",
                "x3 +- hc 0 dx3",
                "x4 +- hc dx3 0",
                "x6 +- r 0 x1",
                "y2 +- vc 0 dx2",
                "y5 +- vc dx2 0",
                "y3 +- vc 0 dx3",
                "y4 +- vc dx3 0",
                "y6 +- b 0 x1",
            },
            new[]
            {
                "M l vc",
                "L x1 y2",
                "L x1 y3",
                "L x3 y3",
                "L x3 x1",
                "L x2 x1",
                "L hc t",
                "L x5 x1",
                "L x4 x1",
                "L x4 y3",
                "L x6 y3",
                "L x6 y2",
                "L r vc",
                "L x6 y5",
                "L x6 y4",
                "L x4 y4",
                "L x4 y6",
                "L x5 y6",
                "L hc b",
                "L x2 y6",
                "L x3 y6",
                "L x3 y4",
                "L x1 y4",
                "L x1 y5",
                "Z",
            }),

        // ECMA-376 blockArc: annulus band from adj1 (start angle) sweeping to adj2
        // (end angle, wrapping through +360° when the raw delta is negative) with
        // band thickness adj3 as a fraction of ss.
        ["blockArc"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 10800000,
                ["adj2"] = 0,
                ["adj3"] = 25000,
            },
            new[]
            {
                "stAng pin 0 adj1 21599999",
                "istAng pin 0 adj2 21599999",
                "a3 pin 0 adj3 50000",
                "sw11 +- istAng 0 stAng",
                "sw12 +- sw11 21600000 0",
                "swAng ?: sw11 sw11 sw12",
                "iswAng +- 0 0 swAng",
                "wt1 sin wd2 stAng",
                "ht1 cos hd2 stAng",
                "wt3 sin wd2 istAng",
                "ht3 cos hd2 istAng",
                "dx1 cat2 wd2 ht1 wt1",
                "dy1 sat2 hd2 ht1 wt1",
                "dx3 cat2 wd2 ht3 wt3",
                "dy3 sat2 hd2 ht3 wt3",
                "x1 +- hc dx1 0",
                "y1 +- vc dy1 0",
                "x3 +- hc dx3 0",
                "y3 +- vc dy3 0",
                "dr */ ss a3 100000",
                "iwd2 +- wd2 0 dr",
                "ihd2 +- hd2 0 dr",
                "wt2 sin iwd2 istAng",
                "ht2 cos ihd2 istAng",
                "wt4 sin iwd2 stAng",
                "ht4 cos ihd2 stAng",
                "dx2 cat2 iwd2 ht2 wt2",
                "dy2 sat2 ihd2 ht2 wt2",
                "dx4 cat2 iwd2 ht4 wt4",
                "dy4 sat2 ihd2 ht4 wt4",
                "x2 +- hc dx2 0",
                "y2 +- vc dy2 0",
                "x4 +- hc dx4 0",
                "y4 +- vc dy4 0",
            },
            new[]
            {
                "M x1 y1",
                "A wd2 hd2 stAng swAng",
                "L x2 y2",
                "A iwd2 ihd2 istAng iswAng",
                "Z",
            }),

        // ECMA-376 leftRightRibbon: horizontal ribbon with arrow tips on both
        // ends and a fold-under center band. adj1 = fold depth, adj2 = tip
        // inset (both fractions of ss·2/h), adj3 = fold curvature (arc height).
        // Only the main fill path is emitted — the darkenLess fold detail path
        // and the stroke-only path add no silhouette.
        ["leftRightRibbon"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 50000,
                ["adj2"] = 50000,
                ["adj3"] = 16667,
            },
            new[]
            {
                "a3 pin 0 adj3 33333",
                "maxAdj1 +- 100000 0 a3",
                "a1 pin 0 adj1 maxAdj1",
                "wd32 */ w 1 32",
                "w1 +- wd2 0 wd32",
                "maxAdj2 */ 100000 w1 ss",
                "a2 pin 0 adj2 maxAdj2",
                "x1 */ ss a2 100000",
                "x4 +- r 0 x1",
                "dy1 */ h a1 200000",
                "dy2 */ h a3 -200000",
                "ly1 +- vc dy2 dy1",
                "ry4 +- vc dy1 dy2",
                "ly2 +- ly1 dy1 0",
                "ry3 +- b 0 ly2",
                "ly4 */ ly2 2 1",
                "ry1 +- b 0 ly4",
                "ly3 +- ly4 0 ly1",
                "ry2 +- b 0 ly3",
                "hR */ a3 ss 400000",
                "x2 +- hc 0 wd32",
            },
            new[]
            {
                "M l ly2",
                "L x1 t",
                "L x1 ly1",
                "L hc ly1",
                "A wd32 hR 3cd4 cd2",
                "A wd32 hR 3cd4 -10800000",
                "L x4 ry2",
                "L x4 ry1",
                "L r ry3",
                "L x4 b",
                "L x4 ry4",
                "L hc ry4",
                "A wd32 hR cd4 cd4",
                "L x2 ly3",
                "L x1 ly3",
                "L x1 ly4",
                "Z",
            }),

        // ECMA-376 upArrowCallout: rectangular callout body with an up-arrow
        // shaft+head rising from its top edge. adj1 = shaft half-thickness,
        // adj2 = head half-width (both fractions of ss), adj3 = head height
        // (fraction of ss), adj4 = callout-body height (fraction of h).
        ["upArrowCallout"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 25000,
                ["adj2"] = 25000,
                ["adj3"] = 25000,
                ["adj4"] = 64977,
            },
            new[]
            {
                "maxAdj2 */ 50000 w ss",
                "a2 pin 0 adj2 maxAdj2",
                "maxAdj1 */ a2 2 1",
                "a1 pin 0 adj1 maxAdj1",
                "maxAdj3 */ 100000 h ss",
                "a3 pin 0 adj3 maxAdj3",
                "q2 */ a3 ss h",
                "maxAdj4 +- 100000 0 q2",
                "a4 pin 0 adj4 maxAdj4",
                "dx1 */ ss a2 100000",
                "dx2 */ ss a1 200000",
                "x1 +- hc 0 dx1",
                "x2 +- hc 0 dx2",
                "x3 +- hc dx2 0",
                "x4 +- hc dx1 0",
                "y1 */ ss a3 100000",
                "dy2 */ h a4 100000",
                "y2 +- b 0 dy2",
            },
            new[]
            {
                "M l y2",
                "L x2 y2",
                "L x2 y1",
                "L x1 y1",
                "L hc t",
                "L x4 y1",
                "L x3 y1",
                "L x3 y2",
                "L r y2",
                "L r b",
                "L l b",
                "Z",
            }),

        ["gear6"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 15000,
                ["adj2"] = 3526,
            },
            new[]
            {
                "a1 pin 0 adj1 20000",
                "a2 pin 0 adj2 5358",
                "th */ ss a1 100000",
                "lFD */ ss a2 100000",
                "th2 */ th 1 2",
                "l2 */ lFD 1 2",
                "l3 +- th2 l2 0",
                "rh +- hd2 0 th",
                "rw +- wd2 0 th",
                "dr +- rw 0 rh",
                "maxr ?: dr rh rw",
                "ha at2 maxr l3",
                "aA1 +- 19800000 0 ha",
                "aD1 +- 19800000 ha 0",
                "ta11 cos rw aA1",
                "ta12 sin rh aA1",
                "bA1 at2 ta11 ta12",
                "cta1 cos rh bA1",
                "sta1 sin rw bA1",
                "ma1 mod cta1 sta1 0",
                "na1 */ rw rh ma1",
                "dxa1 cos na1 bA1",
                "dya1 sin na1 bA1",
                "xA1 +- hc dxa1 0",
                "yA1 +- vc dya1 0",
                "td11 cos rw aD1",
                "td12 sin rh aD1",
                "bD1 at2 td11 td12",
                "ctd1 cos rh bD1",
                "std1 sin rw bD1",
                "md1 mod ctd1 std1 0",
                "nd1 */ rw rh md1",
                "dxd1 cos nd1 bD1",
                "dyd1 sin nd1 bD1",
                "xD1 +- hc dxd1 0",
                "yD1 +- vc dyd1 0",
                "xAD1 +- xA1 0 xD1",
                "yAD1 +- yA1 0 yD1",
                "lAD1 mod xAD1 yAD1 0",
                "a1 at2 yAD1 xAD1",
                "dxF1 sin lFD a1",
                "dyF1 cos lFD a1",
                "xF1 +- xD1 dxF1 0",
                "yF1 +- yD1 dyF1 0",
                "xE1 +- xA1 0 dxF1",
                "yE1 +- yA1 0 dyF1",
                "yC1t sin th a1",
                "xC1t cos th a1",
                "yC1 +- yF1 yC1t 0",
                "xC1 +- xF1 0 xC1t",
                "yB1 +- yE1 yC1t 0",
                "xB1 +- xE1 0 xC1t",
                "aD6 +- 3cd4 ha 0",
                "td61 cos rw aD6",
                "td62 sin rh aD6",
                "bD6 at2 td61 td62",
                "ctd6 cos rh bD6",
                "std6 sin rw bD6",
                "md6 mod ctd6 std6 0",
                "nd6 */ rw rh md6",
                "dxd6 cos nd6 bD6",
                "dyd6 sin nd6 bD6",
                "xD6 +- hc dxd6 0",
                "yD6 +- vc dyd6 0",
                "xA6 +- hc 0 dxd6",
                "xF6 +- xD6 0 lFD",
                "xE6 +- xA6 lFD 0",
                "yC6 +- yD6 0 th",
                "swAng1 +- bA1 0 bD6",
                "aA2 +- 1800000 0 ha",
                "aD2 +- 1800000 ha 0",
                "ta21 cos rw aA2",
                "ta22 sin rh aA2",
                "bA2 at2 ta21 ta22",
                "yA2 +- h 0 yD1",
                "td21 cos rw aD2",
                "td22 sin rh aD2",
                "bD2 at2 td21 td22",
                "yD2 +- h 0 yA1",
                "yC2 +- h 0 yB1",
                "yB2 +- h 0 yC1",
                "xB2 val xC1",
                "swAng2 +- bA2 0 bD1",
                "aD3 +- cd4 ha 0",
                "td31 cos rw aD3",
                "td32 sin rh aD3",
                "bD3 at2 td31 td32",
                "yD3 +- h 0 yD6",
                "yB3 +- h 0 yC6",
                "aD4 +- 9000000 ha 0",
                "td41 cos rw aD4",
                "td42 sin rh aD4",
                "bD4 at2 td41 td42",
                "xD4 +- w 0 xD1",
                "xC4 +- w 0 xC1",
                "xB4 +- w 0 xB1",
                "aD5 +- 12600000 ha 0",
                "td51 cos rw aD5",
                "td52 sin rh aD5",
                "bD5 at2 td51 td52",
                "xD5 +- w 0 xA1",
                "xC5 +- w 0 xB1",
                "xB5 +- w 0 xC1",
                "xCxn1 +/ xB1 xC1 2",
                "yCxn1 +/ yB1 yC1 2",
                "yCxn2 +- b 0 yCxn1",
                "xCxn4 +/ r 0 xCxn1",
            },
            new[]
            {
                "M xA1 yA1",
                "L xB1 yB1",
                "L xC1 yC1",
                "L xD1 yD1",
                "A rw rh bD1 swAng2",
                "L xC1 yB2",
                "L xB1 yC2",
                "L xA1 yD2",
                "A rw rh bD2 swAng1",
                "L xF6 yB3",
                "L xE6 yB3",
                "L xA6 yD3",
                "A rw rh bD3 swAng1",
                "L xB4 yC2",
                "L xC4 yB2",
                "L xD4 yA2",
                "A rw rh bD4 swAng2",
                "L xB5 yC1",
                "L xC5 yB1",
                "L xD5 yA1",
                "A rw rh bD5 swAng1",
                "L xE6 yC6",
                "L xF6 yC6",
                "L xD6 yD6",
                "A rw rh bD6 swAng1",
                "Z",
            }),

        ["gear9"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 10000,
                ["adj2"] = 1763,
            },
            new[]
            {
                "a1 pin 0 adj1 20000",
                "a2 pin 0 adj2 2679",
                "th */ ss a1 100000",
                "lFD */ ss a2 100000",
                "th2 */ th 1 2",
                "l2 */ lFD 1 2",
                "l3 +- th2 l2 0",
                "rh +- hd2 0 th",
                "rw +- wd2 0 th",
                "dr +- rw 0 rh",
                "maxr ?: dr rh rw",
                "ha at2 maxr l3",
                "aA1 +- 18600000 0 ha",
                "aD1 +- 18600000 ha 0",
                "ta11 cos rw aA1",
                "ta12 sin rh aA1",
                "bA1 at2 ta11 ta12",
                "cta1 cos rh bA1",
                "sta1 sin rw bA1",
                "ma1 mod cta1 sta1 0",
                "na1 */ rw rh ma1",
                "dxa1 cos na1 bA1",
                "dya1 sin na1 bA1",
                "xA1 +- hc dxa1 0",
                "yA1 +- vc dya1 0",
                "td11 cos rw aD1",
                "td12 sin rh aD1",
                "bD1 at2 td11 td12",
                "ctd1 cos rh bD1",
                "std1 sin rw bD1",
                "md1 mod ctd1 std1 0",
                "nd1 */ rw rh md1",
                "dxd1 cos nd1 bD1",
                "dyd1 sin nd1 bD1",
                "xD1 +- hc dxd1 0",
                "yD1 +- vc dyd1 0",
                "xAD1 +- xA1 0 xD1",
                "yAD1 +- yA1 0 yD1",
                "lAD1 mod xAD1 yAD1 0",
                "a1 at2 yAD1 xAD1",
                "dxF1 sin lFD a1",
                "dyF1 cos lFD a1",
                "xF1 +- xD1 dxF1 0",
                "yF1 +- yD1 dyF1 0",
                "xE1 +- xA1 0 dxF1",
                "yE1 +- yA1 0 dyF1",
                "yC1t sin th a1",
                "xC1t cos th a1",
                "yC1 +- yF1 yC1t 0",
                "xC1 +- xF1 0 xC1t",
                "yB1 +- yE1 yC1t 0",
                "xB1 +- xE1 0 xC1t",
                "aA2 +- 21000000 0 ha",
                "aD2 +- 21000000 ha 0",
                "ta21 cos rw aA2",
                "ta22 sin rh aA2",
                "bA2 at2 ta21 ta22",
                "cta2 cos rh bA2",
                "sta2 sin rw bA2",
                "ma2 mod cta2 sta2 0",
                "na2 */ rw rh ma2",
                "dxa2 cos na2 bA2",
                "dya2 sin na2 bA2",
                "xA2 +- hc dxa2 0",
                "yA2 +- vc dya2 0",
                "td21 cos rw aD2",
                "td22 sin rh aD2",
                "bD2 at2 td21 td22",
                "ctd2 cos rh bD2",
                "std2 sin rw bD2",
                "md2 mod ctd2 std2 0",
                "nd2 */ rw rh md2",
                "dxd2 cos nd2 bD2",
                "dyd2 sin nd2 bD2",
                "xD2 +- hc dxd2 0",
                "yD2 +- vc dyd2 0",
                "xAD2 +- xA2 0 xD2",
                "yAD2 +- yA2 0 yD2",
                "lAD2 mod xAD2 yAD2 0",
                "a2 at2 yAD2 xAD2",
                "dxF2 sin lFD a2",
                "dyF2 cos lFD a2",
                "xF2 +- xD2 dxF2 0",
                "yF2 +- yD2 dyF2 0",
                "xE2 +- xA2 0 dxF2",
                "yE2 +- yA2 0 dyF2",
                "yC2t sin th a2",
                "xC2t cos th a2",
                "yC2 +- yF2 yC2t 0",
                "xC2 +- xF2 0 xC2t",
                "yB2 +- yE2 yC2t 0",
                "xB2 +- xE2 0 xC2t",
                "swAng1 +- bA2 0 bD1",
                "aA3 +- 1800000 0 ha",
                "aD3 +- 1800000 ha 0",
                "ta31 cos rw aA3",
                "ta32 sin rh aA3",
                "bA3 at2 ta31 ta32",
                "cta3 cos rh bA3",
                "sta3 sin rw bA3",
                "ma3 mod cta3 sta3 0",
                "na3 */ rw rh ma3",
                "dxa3 cos na3 bA3",
                "dya3 sin na3 bA3",
                "xA3 +- hc dxa3 0",
                "yA3 +- vc dya3 0",
                "td31 cos rw aD3",
                "td32 sin rh aD3",
                "bD3 at2 td31 td32",
                "ctd3 cos rh bD3",
                "std3 sin rw bD3",
                "md3 mod ctd3 std3 0",
                "nd3 */ rw rh md3",
                "dxd3 cos nd3 bD3",
                "dyd3 sin nd3 bD3",
                "xD3 +- hc dxd3 0",
                "yD3 +- vc dyd3 0",
                "xAD3 +- xA3 0 xD3",
                "yAD3 +- yA3 0 yD3",
                "lAD3 mod xAD3 yAD3 0",
                "a3 at2 yAD3 xAD3",
                "dxF3 sin lFD a3",
                "dyF3 cos lFD a3",
                "xF3 +- xD3 dxF3 0",
                "yF3 +- yD3 dyF3 0",
                "xE3 +- xA3 0 dxF3",
                "yE3 +- yA3 0 dyF3",
                "yC3t sin th a3",
                "xC3t cos th a3",
                "yC3 +- yF3 yC3t 0",
                "xC3 +- xF3 0 xC3t",
                "yB3 +- yE3 yC3t 0",
                "xB3 +- xE3 0 xC3t",
                "swAng2 +- bA3 0 bD2",
                "aA4 +- 4200000 0 ha",
                "aD4 +- 4200000 ha 0",
                "ta41 cos rw aA4",
                "ta42 sin rh aA4",
                "bA4 at2 ta41 ta42",
                "cta4 cos rh bA4",
                "sta4 sin rw bA4",
                "ma4 mod cta4 sta4 0",
                "na4 */ rw rh ma4",
                "dxa4 cos na4 bA4",
                "dya4 sin na4 bA4",
                "xA4 +- hc dxa4 0",
                "yA4 +- vc dya4 0",
                "td41 cos rw aD4",
                "td42 sin rh aD4",
                "bD4 at2 td41 td42",
                "ctd4 cos rh bD4",
                "std4 sin rw bD4",
                "md4 mod ctd4 std4 0",
                "nd4 */ rw rh md4",
                "dxd4 cos nd4 bD4",
                "dyd4 sin nd4 bD4",
                "xD4 +- hc dxd4 0",
                "yD4 +- vc dyd4 0",
                "xAD4 +- xA4 0 xD4",
                "yAD4 +- yA4 0 yD4",
                "lAD4 mod xAD4 yAD4 0",
                "a4 at2 yAD4 xAD4",
                "dxF4 sin lFD a4",
                "dyF4 cos lFD a4",
                "xF4 +- xD4 dxF4 0",
                "yF4 +- yD4 dyF4 0",
                "xE4 +- xA4 0 dxF4",
                "yE4 +- yA4 0 dyF4",
                "yC4t sin th a4",
                "xC4t cos th a4",
                "yC4 +- yF4 yC4t 0",
                "xC4 +- xF4 0 xC4t",
                "yB4 +- yE4 yC4t 0",
                "xB4 +- xE4 0 xC4t",
                "swAng3 +- bA4 0 bD3",
                "aA5 +- 6600000 0 ha",
                "aD5 +- 6600000 ha 0",
                "ta51 cos rw aA5",
                "ta52 sin rh aA5",
                "bA5 at2 ta51 ta52",
                "td51 cos rw aD5",
                "td52 sin rh aD5",
                "bD5 at2 td51 td52",
                "xD5 +- w 0 xA4",
                "xC5 +- w 0 xB4",
                "xB5 +- w 0 xC4",
                "swAng4 +- bA5 0 bD4",
                "aD6 +- 9000000 ha 0",
                "td61 cos rw aD6",
                "td62 sin rh aD6",
                "bD6 at2 td61 td62",
                "xD6 +- w 0 xA3",
                "xC6 +- w 0 xB3",
                "xB6 +- w 0 xC3",
                "aD7 +- 11400000 ha 0",
                "td71 cos rw aD7",
                "td72 sin rh aD7",
                "bD7 at2 td71 td72",
                "xD7 +- w 0 xA2",
                "xC7 +- w 0 xB2",
                "xB7 +- w 0 xC2",
                "aD8 +- 13800000 ha 0",
                "td81 cos rw aD8",
                "td82 sin rh aD8",
                "bD8 at2 td81 td82",
                "xA8 +- w 0 xD1",
                "xD8 +- w 0 xA1",
                "xC8 +- w 0 xB1",
                "xB8 +- w 0 xC1",
                "aA9 +- 3cd4 0 ha",
                "aD9 +- 3cd4 ha 0",
                "td91 cos rw aD9",
                "td92 sin rh aD9",
                "bD9 at2 td91 td92",
                "ctd9 cos rh bD9",
                "std9 sin rw bD9",
                "md9 mod ctd9 std9 0",
                "nd9 */ rw rh md9",
                "dxd9 cos nd9 bD9",
                "dyd9 sin nd9 bD9",
                "xD9 +- hc dxd9 0",
                "yD9 +- vc dyd9 0",
                "ta91 cos rw aA9",
                "ta92 sin rh aA9",
                "bA9 at2 ta91 ta92",
                "xA9 +- hc 0 dxd9",
                "xF9 +- xD9 0 lFD",
                "xE9 +- xA9 lFD 0",
                "yC9 +- yD9 0 th",
                "swAng5 +- bA9 0 bD8",
                "xCxn1 +/ xB1 xC1 2",
                "yCxn1 +/ yB1 yC1 2",
                "xCxn2 +/ xB2 xC2 2",
                "yCxn2 +/ yB2 yC2 2",
                "xCxn3 +/ xB3 xC3 2",
                "yCxn3 +/ yB3 yC3 2",
                "xCxn4 +/ xB4 xC4 2",
                "yCxn4 +/ yB4 yC4 2",
                "xCxn5 +/ r 0 xCxn4",
                "xCxn6 +/ r 0 xCxn3",
                "xCxn7 +/ r 0 xCxn2",
                "xCxn8 +/ r 0 xCxn1",
            },
            new[]
            {
                "M xA1 yA1",
                "L xB1 yB1",
                "L xC1 yC1",
                "L xD1 yD1",
                "A rw rh bD1 swAng1",
                "L xB2 yB2",
                "L xC2 yC2",
                "L xD2 yD2",
                "A rw rh bD2 swAng2",
                "L xB3 yB3",
                "L xC3 yC3",
                "L xD3 yD3",
                "A rw rh bD3 swAng3",
                "L xB4 yB4",
                "L xC4 yC4",
                "L xD4 yD4",
                "A rw rh bD4 swAng4",
                "L xB5 yC4",
                "L xC5 yB4",
                "L xD5 yA4",
                "A rw rh bD5 swAng3",
                "L xB6 yC3",
                "L xC6 yB3",
                "L xD6 yA3",
                "A rw rh bD6 swAng2",
                "L xB7 yC2",
                "L xC7 yB2",
                "L xD7 yA2",
                "A rw rh bD7 swAng1",
                "L xB8 yC1",
                "L xC8 yB1",
                "L xD8 yA1",
                "A rw rh bD8 swAng5",
                "L xE9 yC9",
                "L xF9 yC9",
                "L xD9 yD9",
                "A rw rh bD9 swAng5",
                "Z",
            }),

        ["circularArrow"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 12500,
                ["adj2"] = 1142319,
                ["adj3"] = 20457681,
                ["adj4"] = 10800000,
                ["adj5"] = 12500,
            },
            new[]
            {
                "a5 pin 0 adj5 25000",
                "maxAdj1 */ a5 2 1",
                "a1 pin 0 adj1 maxAdj1",
                "enAng pin 1 adj3 21599999",
                "stAng pin 0 adj4 21599999",
                "th */ ss a1 100000",
                "thh */ ss a5 100000",
                "th2 */ th 1 2",
                "rw1 +- wd2 th2 thh",
                "rh1 +- hd2 th2 thh",
                "rw2 +- rw1 0 th",
                "rh2 +- rh1 0 th",
                "rw3 +- rw2 th2 0",
                "rh3 +- rh2 th2 0",
                "wtH sin rw3 enAng",
                "htH cos rh3 enAng",
                "dxH cat2 rw3 htH wtH",
                "dyH sat2 rh3 htH wtH",
                "xH +- hc dxH 0",
                "yH +- vc dyH 0",
                "rI min rw2 rh2",
                "u1 */ dxH dxH 1",
                "u2 */ dyH dyH 1",
                "u3 */ rI rI 1",
                "u4 +- u1 0 u3",
                "u5 +- u2 0 u3",
                "u6 */ u4 u5 u1",
                "u7 */ u6 1 u2",
                "u8 +- 1 0 u7",
                "u9 sqrt u8",
                "u10 */ u4 1 dxH",
                "u11 */ u10 1 dyH",
                "u12 +/ 1 u9 u11",
                "u13 at2 1 u12",
                "u14 +- u13 21600000 0",
                "u15 ?: u13 u13 u14",
                "u16 +- u15 0 enAng",
                "u17 +- u16 21600000 0",
                "u18 ?: u16 u16 u17",
                "u19 +- u18 0 cd2",
                "u20 +- u18 0 21600000",
                "u21 ?: u19 u20 u18",
                "maxAng abs u21",
                "aAng pin 0 adj2 maxAng",
                "ptAng +- enAng aAng 0",
                "wtA sin rw3 ptAng",
                "htA cos rh3 ptAng",
                "dxA cat2 rw3 htA wtA",
                "dyA sat2 rh3 htA wtA",
                "xA +- hc dxA 0",
                "yA +- vc dyA 0",
                "wtE sin rw1 stAng",
                "htE cos rh1 stAng",
                "dxE cat2 rw1 htE wtE",
                "dyE sat2 rh1 htE wtE",
                "xE +- hc dxE 0",
                "yE +- vc dyE 0",
                "dxG cos thh ptAng",
                "dyG sin thh ptAng",
                "xG +- xH dxG 0",
                "yG +- yH dyG 0",
                "dxB cos thh ptAng",
                "dyB sin thh ptAng",
                "xB +- xH 0 dxB 0",
                "yB +- yH 0 dyB 0",
                "sx1 +- xB 0 hc",
                "sy1 +- yB 0 vc",
                "sx2 +- xG 0 hc",
                "sy2 +- yG 0 vc",
                "rO min rw1 rh1",
                "x1O */ sx1 rO rw1",
                "y1O */ sy1 rO rh1",
                "x2O */ sx2 rO rw1",
                "y2O */ sy2 rO rh1",
                "dxO +- x2O 0 x1O",
                "dyO +- y2O 0 y1O",
                "dO mod dxO dyO 0",
                "q1 */ x1O y2O 1",
                "q2 */ x2O y1O 1",
                "DO +- q1 0 q2",
                "q3 */ rO rO 1",
                "q4 */ dO dO 1",
                "q5 */ q3 q4 1",
                "q6 */ DO DO 1",
                "q7 +- q5 0 q6",
                "q8 max q7 0",
                "sdelO sqrt q8",
                "ndyO */ dyO -1 1",
                "sdyO ?: ndyO -1 1",
                "q9 */ sdyO dxO 1",
                "q10 */ q9 sdelO 1",
                "q11 */ DO dyO 1",
                "dxF1 +/ q11 q10 q4",
                "q12 +- q11 0 q10",
                "dxF2 */ q12 1 q4",
                "adyO abs dyO",
                "q13 */ adyO sdelO 1",
                "q14 */ DO dxO -1",
                "dyF1 +/ q14 q13 q4",
                "q15 +- q14 0 q13",
                "dyF2 */ q15 1 q4",
                "q16 +- x2O 0 dxF1",
                "q17 +- x2O 0 dxF2",
                "q18 +- y2O 0 dyF1",
                "q19 +- y2O 0 dyF2",
                "q20 mod q16 q18 0",
                "q21 mod q17 q19 0",
                "q22 +- q21 0 q20",
                "dxF ?: q22 dxF1 dxF2",
                "dyF ?: q22 dyF1 dyF2",
                "sdxF */ dxF rw1 rO",
                "sdyF */ dyF rh1 rO",
                "xF +- hc sdxF 0",
                "yF +- vc sdyF 0",
                "x1I */ sx1 rI rw2",
                "y1I */ sy1 rI rh2",
                "x2I */ sx2 rI rw2",
                "y2I */ sy2 rI rh2",
                "dxI +- x2I 0 x1I",
                "dyI +- y2I 0 y1I",
                "dI mod dxI dyI 0",
                "v1 */ x1I y2I 1",
                "v2 */ x2I y1I 1",
                "DI +- v1 0 v2",
                "v3 */ rI rI 1",
                "v4 */ dI dI 1",
                "v5 */ v3 v4 1",
                "v6 */ DI DI 1",
                "v7 +- v5 0 v6",
                "v8 max v7 0",
                "sdelI sqrt v8",
                "v9 */ sdyO dxI 1",
                "v10 */ v9 sdelI 1",
                "v11 */ DI dyI 1",
                "dxC1 +/ v11 v10 v4",
                "v12 +- v11 0 v10",
                "dxC2 */ v12 1 v4",
                "adyI abs dyI",
                "v13 */ adyI sdelI 1",
                "v14 */ DI dxI -1",
                "dyC1 +/ v14 v13 v4",
                "v15 +- v14 0 v13",
                "dyC2 */ v15 1 v4",
                "v16 +- x1I 0 dxC1",
                "v17 +- x1I 0 dxC2",
                "v18 +- y1I 0 dyC1",
                "v19 +- y1I 0 dyC2",
                "v20 mod v16 v18 0",
                "v21 mod v17 v19 0",
                "v22 +- v21 0 v20",
                "dxC ?: v22 dxC1 dxC2",
                "dyC ?: v22 dyC1 dyC2",
                "sdxC */ dxC rw2 rI",
                "sdyC */ dyC rh2 rI",
                "xC +- hc sdxC 0",
                "yC +- vc sdyC 0",
                "ist0 at2 sdxC sdyC",
                "ist1 +- ist0 21600000 0",
                "istAng ?: ist0 ist0 ist1",
                "isw1 +- stAng 0 istAng",
                "isw2 +- isw1 0 21600000",
                "iswAng ?: isw1 isw2 isw1",
                "p1 +- xF 0 xC",
                "p2 +- yF 0 yC",
                "p3 mod p1 p2 0",
                "p4 */ p3 1 2",
                "p5 +- p4 0 thh",
                "xGp ?: p5 xF xG",
                "yGp ?: p5 yF yG",
                "xBp ?: p5 xC xB",
                "yBp ?: p5 yC yB",
                "en0 at2 sdxF sdyF",
                "en1 +- en0 21600000 0",
                "en2 ?: en0 en0 en1",
                "sw0 +- en2 0 stAng",
                "sw1 +- sw0 21600000 0",
                "swAng ?: sw0 sw0 sw1",
                "wtI sin rw3 stAng",
                "htI cos rh3 stAng",
                "dxI cat2 rw3 htI wtI",
                "dyI sat2 rh3 htI wtI",
                "xI +- hc dxI 0",
                "yI +- vc dyI 0",
                "aI +- stAng 0 cd4",
                "aA +- ptAng cd4 0",
                "aB +- ptAng cd2 0",
                "idx cos rw1 2700000",
                "idy sin rh1 2700000",
                "il +- hc 0 idx",
                "ir +- hc idx 0",
                "it +- vc 0 idy",
                "ib +- vc idy 0",
            },
            new[]
            {
                "M xE yE",
                "A rw1 rh1 stAng swAng",
                "L xGp yGp",
                "L xA yA",
                "L xBp yBp",
                "L xC yC",
                "A rw2 rh2 istAng iswAng",
                "Z",
            }),

        ["leftCircularArrow"] = new SmartArtPresetGeometry.PresetDef(
            new Dictionary<string, double>
            {
                ["adj1"] = 12500,
                ["adj2"] = -1142319,
                ["adj3"] = 1142319,
                ["adj4"] = 10800000,
                ["adj5"] = 12500,
            },
            new[]
            {
                "a5 pin 0 adj5 25000",
                "maxAdj1 */ a5 2 1",
                "a1 pin 0 adj1 maxAdj1",
                "enAng pin 1 adj3 21599999",
                "stAng pin 0 adj4 21599999",
                "th */ ss a1 100000",
                "thh */ ss a5 100000",
                "th2 */ th 1 2",
                "rw1 +- wd2 th2 thh",
                "rh1 +- hd2 th2 thh",
                "rw2 +- rw1 0 th",
                "rh2 +- rh1 0 th",
                "rw3 +- rw2 th2 0",
                "rh3 +- rh2 th2 0",
                "wtH sin rw3 enAng",
                "htH cos rh3 enAng",
                "dxH cat2 rw3 htH wtH",
                "dyH sat2 rh3 htH wtH",
                "xH +- hc dxH 0",
                "yH +- vc dyH 0",
                "rI min rw2 rh2",
                "u1 */ dxH dxH 1",
                "u2 */ dyH dyH 1",
                "u3 */ rI rI 1",
                "u4 +- u1 0 u3",
                "u5 +- u2 0 u3",
                "u6 */ u4 u5 u1",
                "u7 */ u6 1 u2",
                "u8 +- 1 0 u7",
                "u9 sqrt u8",
                "u10 */ u4 1 dxH",
                "u11 */ u10 1 dyH",
                "u12 +/ 1 u9 u11",
                "u13 at2 1 u12",
                "u14 +- u13 21600000 0",
                "u15 ?: u13 u13 u14",
                "u16 +- u15 0 enAng",
                "u17 +- u16 21600000 0",
                "u18 ?: u16 u16 u17",
                "u19 +- u18 0 cd2",
                "u20 +- u18 0 21600000",
                "u21 ?: u19 u20 u18",
                "u22 abs u21",
                "minAng */ u22 -1 1",
                "u23 abs adj2",
                "a2 */ u23 -1 1",
                "aAng pin minAng a2 0",
                "ptAng +- enAng aAng 0",
                "wtA sin rw3 ptAng",
                "htA cos rh3 ptAng",
                "dxA cat2 rw3 htA wtA",
                "dyA sat2 rh3 htA wtA",
                "xA +- hc dxA 0",
                "yA +- vc dyA 0",
                "wtE sin rw1 stAng",
                "htE cos rh1 stAng",
                "dxE cat2 rw1 htE wtE",
                "dyE sat2 rh1 htE wtE",
                "xE +- hc dxE 0",
                "yE +- vc dyE 0",
                "wtD sin rw2 stAng",
                "htD cos rh2 stAng",
                "dxD cat2 rw2 htD wtD",
                "dyD sat2 rh2 htD wtD",
                "xD +- hc dxD 0",
                "yD +- vc dyD 0",
                "dxG cos thh ptAng",
                "dyG sin thh ptAng",
                "xG +- xH dxG 0",
                "yG +- yH dyG 0",
                "dxB cos thh ptAng",
                "dyB sin thh ptAng",
                "xB +- xH 0 dxB 0",
                "yB +- yH 0 dyB 0",
                "sx1 +- xB 0 hc",
                "sy1 +- yB 0 vc",
                "sx2 +- xG 0 hc",
                "sy2 +- yG 0 vc",
                "rO min rw1 rh1",
                "x1O */ sx1 rO rw1",
                "y1O */ sy1 rO rh1",
                "x2O */ sx2 rO rw1",
                "y2O */ sy2 rO rh1",
                "dxO +- x2O 0 x1O",
                "dyO +- y2O 0 y1O",
                "dO mod dxO dyO 0",
                "q1 */ x1O y2O 1",
                "q2 */ x2O y1O 1",
                "DO +- q1 0 q2",
                "q3 */ rO rO 1",
                "q4 */ dO dO 1",
                "q5 */ q3 q4 1",
                "q6 */ DO DO 1",
                "q7 +- q5 0 q6",
                "q8 max q7 0",
                "sdelO sqrt q8",
                "ndyO */ dyO -1 1",
                "sdyO ?: ndyO -1 1",
                "q9 */ sdyO dxO 1",
                "q10 */ q9 sdelO 1",
                "q11 */ DO dyO 1",
                "dxF1 +/ q11 q10 q4",
                "q12 +- q11 0 q10",
                "dxF2 */ q12 1 q4",
                "adyO abs dyO",
                "q13 */ adyO sdelO 1",
                "q14 */ DO dxO -1",
                "dyF1 +/ q14 q13 q4",
                "q15 +- q14 0 q13",
                "dyF2 */ q15 1 q4",
                "q16 +- x2O 0 dxF1",
                "q17 +- x2O 0 dxF2",
                "q18 +- y2O 0 dyF1",
                "q19 +- y2O 0 dyF2",
                "q20 mod q16 q18 0",
                "q21 mod q17 q19 0",
                "q22 +- q21 0 q20",
                "dxF ?: q22 dxF1 dxF2",
                "dyF ?: q22 dyF1 dyF2",
                "sdxF */ dxF rw1 rO",
                "sdyF */ dyF rh1 rO",
                "xF +- hc sdxF 0",
                "yF +- vc sdyF 0",
                "x1I */ sx1 rI rw2",
                "y1I */ sy1 rI rh2",
                "x2I */ sx2 rI rw2",
                "y2I */ sy2 rI rh2",
                "dxI +- x2I 0 x1I",
                "dyI +- y2I 0 y1I",
                "dI mod dxI dyI 0",
                "v1 */ x1I y2I 1",
                "v2 */ x2I y1I 1",
                "DI +- v1 0 v2",
                "v3 */ rI rI 1",
                "v4 */ dI dI 1",
                "v5 */ v3 v4 1",
                "v6 */ DI DI 1",
                "v7 +- v5 0 v6",
                "v8 max v7 0",
                "sdelI sqrt v8",
                "v9 */ sdyO dxI 1",
                "v10 */ v9 sdelI 1",
                "v11 */ DI dyI 1",
                "dxC1 +/ v11 v10 v4",
                "v12 +- v11 0 v10",
                "dxC2 */ v12 1 v4",
                "adyI abs dyI",
                "v13 */ adyI sdelI 1",
                "v14 */ DI dxI -1",
                "dyC1 +/ v14 v13 v4",
                "v15 +- v14 0 v13",
                "dyC2 */ v15 1 v4",
                "v16 +- x1I 0 dxC1",
                "v17 +- x1I 0 dxC2",
                "v18 +- y1I 0 dyC1",
                "v19 +- y1I 0 dyC2",
                "v20 mod v16 v18 0",
                "v21 mod v17 v19 0",
                "v22 +- v21 0 v20",
                "dxC ?: v22 dxC1 dxC2",
                "dyC ?: v22 dyC1 dyC2",
                "sdxC */ dxC rw2 rI",
                "sdyC */ dyC rh2 rI",
                "xC +- hc sdxC 0",
                "yC +- vc sdyC 0",
                "ist0 at2 sdxC sdyC",
                "ist1 +- ist0 21600000 0",
                "istAng0 ?: ist0 ist0 ist1",
                "isw1 +- stAng 0 istAng0",
                "isw2 +- isw1 21600000 0",
                "iswAng0 ?: isw1 isw1 isw2",
                "istAng +- istAng0 iswAng0 0",
                "iswAng +- 0 0 iswAng0",
                "p1 +- xF 0 xC",
                "p2 +- yF 0 yC",
                "p3 mod p1 p2 0",
                "p4 */ p3 1 2",
                "p5 +- p4 0 thh",
                "xGp ?: p5 xF xG",
                "yGp ?: p5 yF yG",
                "xBp ?: p5 xC xB",
                "yBp ?: p5 yC yB",
                "en0 at2 sdxF sdyF",
                "en1 +- en0 21600000 0",
                "en2 ?: en0 en0 en1",
                "sw0 +- en2 0 stAng",
                "sw1 +- sw0 0 21600000",
                "swAng ?: sw0 sw1 sw0",
                "stAng0 +- stAng swAng 0",
                "swAng0 +- 0 0 swAng",
                "wtI sin rw3 stAng",
                "htI cos rh3 stAng",
                "dxI cat2 rw3 htI wtI",
                "dyI sat2 rh3 htI wtI",
                "xI +- hc dxI 0",
                "yI +- vc dyI 0",
                "aI +- stAng cd4 0",
                "aA +- ptAng 0 cd4",
                "aB +- ptAng cd2 0",
                "idx cos rw1 2700000",
                "idy sin rh1 2700000",
                "il +- hc 0 idx",
                "ir +- hc idx 0",
                "it +- vc 0 idy",
                "ib +- vc idy 0",
            },
            new[]
            {
                "M xE yE",
                "L xD yD",
                "A rw2 rh2 istAng iswAng",
                "L xBp yBp",
                "L xA yA",
                "L xGp yGp",
                "L xF yF",
                "A rw1 rh1 stAng0 swAng0",
                "Z",
            }),

    };
}
