// Generated by OfficeEditor from PPTX

#set text(font: ("Arial", "Helvetica", "Liberation Sans"))

#set page(width: 720.00pt, height: 540.00pt, margin: 0pt)
#set page(fill: rgb("#FFFFFF"))

#place(top + left, dx: 0.00pt, dy: 0.00pt)[#block(width: 566.93pt)[#text(size: 18.00pt)[Typst Source Export]]]
#place(top + left, dx: 0.00pt, dy: 56.69pt)[#block(width: 566.93pt)[#text(size: 18.00pt)[View the generated code]]]

#set page(width: 720.00pt, height: 540.00pt, margin: 0pt)
#set page(fill: rgb("#FFFFFF"))

#pagebreak()

#place(top + left, dx: 0.00pt, dy: 0.00pt)[#block(width: 566.93pt)[#text(size: 18.00pt)[How it works]]]
#place(top + left, dx: 0.00pt, dy: 113.39pt)[#block(width: 566.93pt)[#text(size: 18.00pt)[1. Extract PPTX content]]]
#place(top + left, dx: 0.00pt, dy: 113.39pt)[#block(width: 566.93pt)[#text(size: 18.00pt)[2. Convert to Typst elements]]]
#place(top + left, dx: 0.00pt, dy: 113.39pt)[#block(width: 566.93pt)[#text(size: 18.00pt)[3. Generate Typst source]]]
#place(top + left, dx: 0.00pt, dy: 113.39pt)[#block(width: 566.93pt)[#text(size: 18.00pt)[4. Compile with typstsharp]]]

