using DocxEditor.Core.Builders;
using DocxEditor.Core.Models;
using System.Text.Json;

namespace DocxExamples;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("=== DOCX Examples ===\n");
        
        var outputDir = Path.Combine("..", "output", "docx");
        Directory.CreateDirectory(outputDir);
        
        // Example 1: Basic Document Creation
        BasicDocumentCreation(outputDir);
        
        // Example 2: Markdown Conversion
        MarkdownConversion(outputDir);
        
        // Example 3: JSON Instructions
        JsonInstructions(outputDir);
        
        // Example 4: Variable Detection
        VariableDetection(outputDir);
        
        // Example 5: Template Processing
        TemplateProcessing(outputDir);
        
        Console.WriteLine($"\nAll DOCX examples completed! Check {outputDir}");
    }
    
    static void BasicDocumentCreation(string outputDir)
    {
        Console.WriteLine("1. Creating basic document...");
        
        var path = Path.Combine(outputDir, "01-basic.docx");
        using var builder = DocumentBuilder.Create(path);
        
        builder.AddHeading("Welcome to OfficeEditor", 1);
        builder.AddParagraph("This document was created using the fluent C# API.");
        builder.AddParagraph("You can easily add formatted text, lists, and tables.");
        
        builder.AddHeading("Features", 2);
        builder.AddBulletList(new[] { 
            "Fluent API", 
            "Markdown support", 
            "JSON instructions",
            "Variable replacement" 
        });
        
        builder.AddHeading("Sample Table", 2);
        builder.AddTable(new List<List<string>>
        {
            new() { "Feature", "Status", "Priority" },
            new() { "Tables", "✓ Done", "High" },
            new() { "Images", "✓ Done", "Medium" },
            new() { "Charts", "In Progress", "Low" }
        });
        
        builder.Save();
        Console.WriteLine($"   Created: {path}");
    }
    
    static void MarkdownConversion(string outputDir)
    {
        Console.WriteLine("2. Converting Markdown to DOCX...");
        
        var markdown = @"# Project Proposal

## Executive Summary

This is a **bold** proposal for a new *innovative* project.

## Key Benefits

1. Increased productivity
2. Cost savings
3. Better collaboration

## Implementation

> ""The best way to predict the future is to create it."" - Peter Drucker

### Phase 1: Planning
- Requirements gathering
- Resource allocation
- Timeline definition

### Phase 2: Development
- Core features
- Testing
- Documentation

---

*Generated by OfficeEditor*";
        
        var path = Path.Combine(outputDir, "02-markdown.docx");
        using var builder = DocumentBuilder.Create(path);
        builder.AddMarkdown(markdown);
        builder.Save();
        
        Console.WriteLine($"   Created: {path}");
    }
    
    static void JsonInstructions(string outputDir)
    {
        Console.WriteLine("3. Using JSON instructions...");
        
        // Create a template first
        var templatePath = Path.Combine(outputDir, "03-template.docx");
        using (var builder = DocumentBuilder.Create(templatePath))
        {
            builder.AddParagraph("{{companyName}}");
            builder.AddParagraph("{{address}}");
            builder.AddParagraph("Date: {{date}}");
            builder.AddParagraph("");
            builder.AddParagraph("Dear {{clientName}},");
            builder.AddParagraph("");
            builder.AddParagraph("Thank you for your interest in our services.");
            builder.Save();
        }
        
        // Define instructions
        var instructions = new InstructionSet
        {
            Operations = new List<Operation>
            {
                new()
                {
                    Type = "Replace",
                    Target = "{{companyName}}",
                    Content = "Acme Corporation"
                },
                new()
                {
                    Type = "Replace", 
                    Target = "{{address}}",
                    Content = "123 Business Ave, Suite 100"
                },
                new()
                {
                    Type = "Replace",
                    Target = "{{date}}",
                    Content = DateTime.Now.ToString("yyyy-MM-dd")
                },
                new()
                {
                    Type = "Replace",
                    Target = "{{clientName}}",
                    Content = "John Smith"
                }
            }
        };
        
        // Save instructions to JSON
        var instructionsPath = Path.Combine(outputDir, "03-instructions.json");
        File.WriteAllText(instructionsPath, JsonSerializer.Serialize(instructions, new JsonSerializerOptions 
        { 
            WriteIndented = true 
        }));
        
        // Apply instructions
        var outputPath = Path.Combine(outputDir, "03-instructions-result.docx");
        using (var builder = DocumentBuilder.Open(templatePath))
        {
            foreach (var op in instructions.Operations)
            {
                if (op.Type == "Replace")
                {
                    builder.ReplaceText(op.Target, op.Content);
                }
            }
            builder.SaveAs(outputPath);
        }
        
        Console.WriteLine($"   Template: {templatePath}");
        Console.WriteLine($"   Instructions: {instructionsPath}");
        Console.WriteLine($"   Result: {outputPath}");
    }
    
    static void VariableDetection(string outputDir)
    {
        Console.WriteLine("4. Detecting variables in template...");
        
        // Create template with variables
        var templatePath = Path.Combine(outputDir, "04-detection-template.docx");
        using (var builder = DocumentBuilder.Create(templatePath))
        {
            builder.AddParagraph("Invoice for {{customerName}}");
            builder.AddParagraph("Order #: {{orderNumber}}");
            builder.AddParagraph("Total: ${{totalAmount}}");
            builder.AddParagraph("Due date: {{dueDate}}");
            builder.Save();
        }
        
        // Detect variables
        using var detector = DocumentBuilder.Open(templatePath);
        var variables = detector.DetectVariables();
        
        Console.WriteLine($"   Template: {templatePath}");
        Console.WriteLine($"   Found {variables.Count} variables:");
        foreach (var v in variables)
        {
            Console.WriteLine($"     - {v.Name} (at {v.Location})");
        }
    }
    
    static void TemplateProcessing(string outputDir)
    {
        Console.WriteLine("5. Processing template with conditionals...");
        
        // Create template with logic
        var templatePath = Path.Combine(outputDir, "05-logic-template.docx");
        using (var builder = DocumentBuilder.Create(templatePath))
        {
            builder.AddParagraph("Hello {{name}}!");
            builder.AddParagraph("");
            builder.AddParagraph("{{#if isPremium}}");
            builder.AddParagraph("Thank you for being a premium member!");
            builder.AddParagraph("{{/if}}");
            builder.AddParagraph("");
            builder.AddParagraph("Your items:");
            builder.AddParagraph("{{#each items}}");
            builder.AddParagraph("- {{name}}: ${{price}}");
            builder.AddParagraph("{{/each}}");
            builder.Save();
        }
        
        // Process template
        var outputPath = Path.Combine(outputDir, "05-logic-result.docx");
        using (var builder = DocumentBuilder.Open(templatePath))
        {
            var data = new Dictionary<string, object>
            {
                ["name"] = "Alice",
                ["isPremium"] = true,
                ["items"] = new List<Dictionary<string, object>>
                {
                    new() { ["name"] = "Widget", ["price"] = 25 },
                    new() { ["name"] = "Gadget", ["price"] = 50 },
                    new() { ["name"] = "Tool", ["price"] = 75 }
                }
            };
            
            builder.ProcessTemplate(data);
            builder.SaveAs(outputPath);
        }
        
        Console.WriteLine($"   Template: {templatePath}");
        Console.WriteLine($"   Result: {outputPath}");
    }
}

// Helper classes for JSON instructions
public class InstructionSet
{
    public List<Operation> Operations { get; set; } = new();
}

public class Operation
{
    public string Type { get; set; } = "";
    public string Target { get; set; } = "";
    public string Content { get; set; } = "";
}
