using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using PptxEditor.Core.Models;
using Drawing = DocumentFormat.OpenXml.Drawing;

namespace PptxEditor.Core.Converters;

public sealed partial class PptxToTypstConverter
{
    /// <summary>
    /// The global font fallback chain emitted in the <c>#set text(font: …)</c> header.
    /// Per-run <c>font:</c> parameters must repeat this chain (resolved family first):
    /// in Typst a per-element font parameter REPLACES the whole chain, so a single-family
    /// override collapses to the embedded serif fallback when the family is unavailable
    /// in the compiler's font set.
    /// </summary>
    private IReadOnlyList<string> _globalFontFamilies = [];

    public string GenerateTypstSource(TypstPresentation presentation)
    {
        var sb = new StringBuilder();
        
        // Header comment
        sb.AppendLine("// Generated by OfficeEditor from PPTX");
        sb.AppendLine();

        // Build set of fonts we actually have available (embedded or system-known)
        var availableFonts = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var fontName in presentation.FontMetrics.Keys)
        {
            availableFonts.Add(fontName);
            // Also add without " Bold" suffix if present
            if (fontName.EndsWith(" Bold", StringComparison.OrdinalIgnoreCase))
            {
                availableFonts.Add(fontName[..^5].Trim());
            }
        }
        // Add discovered system fonts
        availableFonts.UnionWith(_availableSystemFonts);

        // Add known system fonts as ultimate fallback
        foreach (var f in _knownSystemFonts) availableFonts.Add(f);

        // Font setup with fallback chain
        // Extracted fonts will be loaded from the font-path directory
        var fontFamilies = BuildGlobalFontFamilies(presentation.ThemeFonts, availableFonts);
        _globalFontFamilies = fontFamilies;
        var fontList = string.Join(", ", fontFamilies.Select(f => $"\"{f}\""));
        sb.AppendLine($"#set text(font: ({fontList}))");
        sb.AppendLine();

        // Process each slide
        for (int i = 0; i < presentation.Slides.Count; i++)
        {
            var slide = presentation.Slides[i];
            GenerateSlideSource(sb, slide, i == 0, availableFonts);
        }

        return sb.ToString();
    }

    private void GenerateSlideSource(StringBuilder sb, TypstSlide slide, bool isFirst, HashSet<string> availableFonts)
    {
        // Page setup for this slide
        var width = slide.Layout.Width;
        var height = slide.Layout.Height;
        sb.AppendLine($"#set page(width: {FormatPt(width)}, height: {FormatPt(height)}, margin: 0pt)");

        // Background - must explicitly set for each slide since Typst persists page properties
        if (!string.IsNullOrEmpty(slide.Layout.BackgroundColor))
        {
            sb.AppendLine($"#set page(fill: rgb(\"{slide.Layout.BackgroundColor}\"))");
        }
        else
        {
            // No explicit background means white (window/background color)
            sb.AppendLine("#set page(fill: rgb(\"#FFFFFF\"))");
        }

        sb.AppendLine();

        // Page break before (except first)
        if (!isFirst)
        {
            sb.AppendLine("#pagebreak()");
            sb.AppendLine();
        }

        // Elements
        foreach (var element in slide.Elements)
        {
            GenerateElementSource(sb, element, slide.Layout.Width, availableFonts);
        }

        sb.AppendLine();
    }

    private void GenerateElementSource(StringBuilder sb, TypstElement element, double slideWidth, HashSet<string> availableFonts)
    {
        var xPos = element.X;
        var yPos = element.Y;
        var width = element.Width;
        var height = element.Height;

        var isRotatedText = element.Type == "Text" && element.Text != null && Math.Abs(element.Rotation) > 0.01;
        double padLeft = 0, padTop = 0, padRight = 0, padBottom = 0;

        if (element.Type == "Text" && element.Text != null)
        {
            var text = element.Text;
            var topLeading = Math.Max(0, ((text.LineSpacing ?? text.Formatting.FontSize) - text.Formatting.FontSize) / 2);
            var metricOffset = GetTextMetricOffset(text);

            if (isRotatedText)
            {
                padLeft = text.PaddingLeft;
                padTop = text.PaddingTop + topLeading + metricOffset;
                padRight = text.PaddingRight;
                padBottom = text.PaddingBottom;
            }

            xPos += text.PaddingLeft;
            yPos += text.PaddingTop + topLeading + metricOffset;
            width = Math.Max(0, width - text.PaddingLeft - text.PaddingRight);
            height = Math.Max(0, height - text.PaddingTop - text.PaddingBottom);

            if (text.VerticalAlign == "bottom")
            {
                // Bottom-anchored text is pinned at the bottom inset: the top trims
                // (leading/metric offsets) must not push the block's bottom edge
                // below the element bottom minus the bottom inset.
                height = Math.Max(0, element.Height - text.PaddingBottom - (yPos - element.Y));
            }

            if (!isRotatedText && IsSingleLineAutoFit(text, height) && text.Formatting.Align == "left")
            {
                width = Math.Max(width, slideWidth - xPos - 2);
            }
        }

        var x = FormatPt(xPos);
        var y = FormatPt(yPos);
        var widthStr = FormatPt(width);
        var heightStr = FormatPt(height);

        if (isRotatedText)
        {
            // Rotated text pivots about the text-box centre (PowerPoint semantics):
            // place the untrimmed box, rotate a full-size block about its centre,
            // and apply the text insets inside via #pad. Rotating the
            // padding-trimmed content (the generic path below) would pivot about
            // the content centre, off the box centre by the insets + leading/
            // metric offsets.
            sb.Append($"#place(top + left, dx: {FormatPt(element.X)}, dy: {FormatPt(element.Y)})");
            sb.Append($"[#rotate({element.Rotation.ToString("F1", CultureInfo.InvariantCulture)}deg, origin: center)");
            sb.Append($"[#block(width: {FormatPt(element.Width)}, height: {FormatPt(element.Height)})");
            sb.Append($"[#pad(left: {FormatPt(padLeft)}, top: {FormatPt(padTop)}, right: {FormatPt(padRight)}, bottom: {FormatPt(padBottom)})[");
            GenerateTextSource(sb, element.Text!, widthStr, heightStr, availableFonts);
            sb.AppendLine("]]]]");
            return;
        }

        sb.Append($"#place(top + left, dx: {x}, dy: {y})");
        sb.Append("[");

        // Apply rotation if present
        if (Math.Abs(element.Rotation) > 0.01)
        {
            sb.Append($"#rotate({element.Rotation.ToString("F1", CultureInfo.InvariantCulture)}deg, origin: center)");
            sb.Append("[");
        }

        switch (element.Type)
        {
            case "Text":
                GenerateTextSource(sb, element.Text!, widthStr, heightStr, availableFonts);
                break;
            case "Image":
                GenerateImageSource(sb, element.Image!, widthStr, heightStr);
                break;
            case "Table":
                GenerateTableSource(sb, element.Table!, widthStr, heightStr);
                break;
            case "Shape":
                GenerateShapeSource(sb, element.Shape!, widthStr, heightStr, element.Width, element.Height, element.Rotation);
                break;
        }

        if (Math.Abs(element.Rotation) > 0.01)
        {
            sb.Append("]");
        }

        sb.AppendLine("]");
    }

    private void GenerateTextSource(StringBuilder sb, TypstTextElement text, string width, string? height, HashSet<string> availableFonts)
    {
        var fmt = text.Formatting;

        // Constrain text to original text box width, with height for vertical alignment
        var descentPadded = false;
        if (!string.IsNullOrEmpty(height) && text.VerticalAlign != "top")
        {
            var alignVal = text.VerticalAlign == "center" ? "horizon" : "bottom";
            sb.Append($"#block(width: {width}, height: {height})[#align({alignVal})[");
            if (text.VerticalAlign == "bottom")
            {
                // PowerPoint bottom-anchors the last line's descent; Typst's bottom-edge
                // is the baseline — reserve the descent below the baseline.
                var descent = GetFontDescender(text.Formatting);
                if (descent > 0.01)
                {
                    sb.Append($"#pad(bottom: {FormatPt(descent)})[");
                    descentPadded = true;
                }
            }
        }
        else
        {
            sb.Append($"#block(width: {width})[");
        }

        // PowerPoint has no implicit inter-paragraph gap: spacing comes only from
        // spcBef/spcAft (emitted as explicit #v) and the line pitch. Typst's default
        // par.spacing (~0.65em) would otherwise double-count between list groups.
        sb.Append("#set par(spacing: 0pt)\n");

        // Element-level fallback leading: only when no paragraph carries its own
        // a:lnSpc — per-paragraph emission below supersedes it otherwise (and uses
        // each paragraph's own font size instead of the element default).
        var leading = text.Paragraphs.Any(p => p.LineSpacing.HasValue) ? 0 : GetTypstParagraphLeading(text);
        if (leading > 0.01)
        {
            sb.Append($"#set par(leading: {FormatPt(leading)})\n");
        }

        // Justified text (algn="just") is a Typst par property, not an alignment.
        // PowerPoint justifies by stretching spaces only — Typst would also
        // hyphenate (its default), so disable hyphenation alongside.
        var justify = fmt.Align == "justify";
        if (justify)
        {
            sb.Append("#set par(justify: true)\n");
            sb.Append("#set text(hyphenate: false)\n");
        }

        // Apply horizontal alignment if not left
        if (fmt.Align != "left" && !justify && !string.IsNullOrEmpty(fmt.Align))
        {
            sb.Append($"#align({fmt.Align})[");
        }

        AppendParagraphs(sb, text, availableFonts);

        // Close horizontal alignment wrapper if opened
        if (fmt.Align != "left" && !justify && !string.IsNullOrEmpty(fmt.Align))
        {
            sb.Append("]");
        }

        // Close vertical alignment wrapper if opened
        if (!string.IsNullOrEmpty(height) && text.VerticalAlign != "top")
        {
            sb.Append(descentPadded ? "]]]" : "]]");
        }
        else
        {
            sb.Append("]");
        }
    }

    /// <summary>
    /// The font's descender depth in points (typographic descender, falling back to the
    /// hhea descender), used to reserve descent space below bottom-anchored baselines.
    /// Returns 0 when metrics are unavailable.
    /// </summary>
    private double GetFontDescender(TypstTextFormatting fmt)
    {
        var metrics = GetFontMetrics(ResolveThemeFont(fmt.FontFamily));
        if (metrics == null || metrics.UnitsPerEm <= 0)
        {
            return 0;
        }

        var descender = metrics.TypoDescender != 0 ? metrics.TypoDescender : metrics.HheaDescender;
        return Math.Max(0, -descender) / (double)metrics.UnitsPerEm * fmt.FontSize;
    }

    private void AppendParagraphs(StringBuilder sb, TypstTextElement text, HashSet<string> availableFonts)
    {
        var paragraphs = text.Paragraphs;

        // Group consecutive list paragraphs for unified enum/list emission
        int i = 0;
        while (i < paragraphs.Count)
        {
            var paragraph = paragraphs[i];

            // Determine if this paragraph is a list item
            string content = paragraph.Content;
            bool isLiteralBullet = false;
            string? literalBulletChar = null;
            if (!paragraph.HasBullet && !string.IsNullOrEmpty(content))
            {
                var trimmed = content.TrimStart();
                if (trimmed.StartsWith("- ") || trimmed.StartsWith("• ") || trimmed.StartsWith("* ") || trimmed.StartsWith("o "))
                {
                    isLiteralBullet = true;
                    literalBulletChar = trimmed.Substring(0, 1);
                    var prefixLen = content.Length - trimmed.Length + 2;
                    if (prefixLen > 0 && prefixLen <= content.Length)
                    {
                        content = content.Substring(prefixLen);
                    }
                }
            }

            bool effectiveHasBullet = paragraph.HasBullet || isLiteralBullet;
            string? effectiveBulletChar = paragraph.BulletChar ?? literalBulletChar;
            bool isListItem = !string.IsNullOrEmpty(paragraph.AutoNumberType) || effectiveHasBullet;

            if (!isListItem || string.IsNullOrEmpty(content))
            {
                // Non-list paragraph or empty paragraph - emit individually
                if (i > 0)
                {
                    var prevParagraph = paragraphs[i - 1];
                    bool prevIsList = !string.IsNullOrEmpty(prevParagraph.AutoNumberType) || prevParagraph.HasBullet;
                    bool currIsList = !string.IsNullOrEmpty(paragraph.AutoNumberType) || paragraph.HasBullet;

                    // Only add paragraph break between non-list paragraphs or after list back to normal
                    if (!prevIsList && !currIsList)
                    {
                        sb.Append("\n\n");
                    }
                    else if (prevIsList && !currIsList)
                    {
                        sb.Append("\n\n");
                    }
                    // Don't add extra break when entering a list
                }

                // Emit per-paragraph leading (a:lnSpc) — overrides any element-level fallback.
                // spcPct multiplies the paragraph's own font size, so it must be computed per paragraph.
                AppendParagraphLeading(sb, paragraph);

                // Emit space before if present
                if (paragraph.SpaceBefore > 0.01)
                {
                    sb.Append($"#v({FormatPt(paragraph.SpaceBefore.Value)})");
                }

                if (string.IsNullOrEmpty(content))
                {
                    sb.Append($"#v({FormatPt(text.LineSpacing ?? paragraph.Formatting.FontSize)})\n");
                }
                else
                {
                    if (!string.IsNullOrEmpty(paragraph.AutoNumberType))
                    {
                        var paramStr = BuildTextParameters(paragraph.Formatting, availableFonts);
                        var escapedContent = EscapeTypstText(content);
                        if (paragraph.Formatting.Caps == "all")
                            escapedContent = $"#upper[{escapedContent}]";
                        var enumParams = BuildEnumParams(1, paragraph);
                        sb.Append($"#enum{enumParams}[{paramStr}[{escapedContent}]]");
                    }
                    else if (effectiveHasBullet)
                    {
                        var marker = effectiveBulletChar ?? "•";
                        var markerEscaped = FormatBulletMarker(EscapeTypstText(marker), paragraph.BulletColor);
                        var indent = paragraph.Level > 0 ? $"#h({paragraph.Level * 1.5}em) " : "";
                        var paramStr = BuildTextParameters(paragraph.Formatting, availableFonts);
                        var escapedContent = EscapeTypstText(content);
                        if (paragraph.Formatting.Caps == "all")
                            escapedContent = $"#upper[{escapedContent}]";
                        sb.Append($"{indent}#list(marker: [{markerEscaped}])[{paramStr}[{escapedContent}]]");
                    }
                    else
                    {
                        AppendParagraphContent(sb, paragraph, null, availableFonts);
                    }
                }

                // Emit space after if present
                if (paragraph.SpaceAfter > 0.01)
                {
                    sb.Append($"#v({FormatPt(paragraph.SpaceAfter.Value)})");
                }

                i++;
                continue;
            }

            // Find the end of this list group
            int groupEnd = i;
            for (int j = i + 1; j < paragraphs.Count; j++)
            {
                var nextP = paragraphs[j];
                string nextContent = nextP.Content;
                bool nextIsLiteral = false;
                string? nextLiteralChar = null;
                if (!nextP.HasBullet && !string.IsNullOrEmpty(nextContent))
                {
                    var trimmed = nextContent.TrimStart();
                    if (trimmed.StartsWith("- ") || trimmed.StartsWith("• ") || trimmed.StartsWith("* ") || trimmed.StartsWith("o "))
                    {
                        nextIsLiteral = true;
                        nextLiteralChar = trimmed.Substring(0, 1);
                    }
                }
                bool nextHasBullet = nextP.HasBullet || nextIsLiteral;
                bool nextIsList = !string.IsNullOrEmpty(nextP.AutoNumberType) || nextHasBullet;
                string? nextEffectiveBulletChar = nextP.BulletChar ?? nextLiteralChar;

                // Group only if same list type, level, marker glyph, bullet color and
                // indentation — otherwise PowerPoint renders the items at different
                // depths/styles and a single Typst list would flatten them.
                bool sameIndents = Nullable.Equals(paragraph.MarginLeft, nextP.MarginLeft)
                    && Nullable.Equals(paragraph.Indent, nextP.Indent);
                bool sameType = (!string.IsNullOrEmpty(paragraph.AutoNumberType) && !string.IsNullOrEmpty(nextP.AutoNumberType)
                        && paragraph.Level == nextP.Level && sameIndents)
                    || (effectiveHasBullet && nextHasBullet && paragraph.Level == nextP.Level && sameIndents
                        && effectiveBulletChar == nextEffectiveBulletChar
                        && paragraph.BulletColor == nextP.BulletColor);

                if (!nextIsList || !sameType)
                    break;

                groupEnd = j;
            }

            // Emit the list group
            bool isNumbered = !string.IsNullOrEmpty(paragraph.AutoNumberType);
            int groupSize = groupEnd - i + 1;

            // Check if all items in the group share the same formatting.
            // Compare first-run (collapsed) formatting: paragraph defaults fall back to the
            // 18pt placeholder for mixed-formatting runs, which would inflate the marker
            // glyph and the line height of every item in the group.
            var firstFmt = GetCollapsedRunFormatting(paragraphs[i]);
            bool allSameFormatting = true;
            for (int k = i + 1; k <= groupEnd; k++)
            {
                if (!AreFormattingEqual(firstFmt, GetCollapsedRunFormatting(paragraphs[k])))
                {
                    allSameFormatting = false;
                    break;
                }
            }
            var groupParamStr = allSameFormatting
                ? BuildTextParameters(GetUniformGroupFormatting(paragraphs, i, groupEnd, firstFmt), availableFonts)
                : "";

            // Determine paragraph break before list
            if (i > 0)
            {
                var prevParagraph = paragraphs[i - 1];
                bool prevIsList = !string.IsNullOrEmpty(prevParagraph.AutoNumberType) || prevParagraph.HasBullet;
                if (!prevIsList)
                {
                    // Don't add extra \n\n when entering a list from normal text
                }
                else
                {
                    // Between adjacent list groups (split by level/marker/indent): no blank
                    // line — a Typst parbreak would add par.spacing (~1.2em) on top of the
                    // OOXML spcAft already emitted after the previous group.
                    sb.Append('\n');
                }
            }

            // Emit per-paragraph leading (a:lnSpc) for the list group
            AppendParagraphLeading(sb, paragraphs[i]);

            // Emit space before first list item if present
            var listSpaceBefore = paragraphs[i].SpaceBefore;
            if (listSpaceBefore > 0.01)
            {
                sb.Append($"#v({FormatPt(listSpaceBefore.Value)})");
            }

            if (isNumbered)
            {
                // For numbered lists, find the start number
                int startNum = 1;
                for (int k = 0; k < i; k++)
                {
                    if (!string.IsNullOrEmpty(paragraphs[k].AutoNumberType) && paragraphs[k].Level == paragraph.Level)
                    {
                        startNum++;
                    }
                }

                var enumParams = BuildEnumParams(startNum, paragraph);
                
                if (!string.IsNullOrEmpty(groupParamStr))
                {
                    sb.Append(groupParamStr);
                    sb.Append("[");
                }
                sb.Append($"#enum{enumParams}");

                for (int k = i; k <= groupEnd; k++)
                {
                    var p = paragraphs[k];
                    var pContent = p.Content;
                    // Strip literal bullets if any
                    if (!p.HasBullet && !string.IsNullOrEmpty(pContent))
                    {
                        var trimmed = pContent.TrimStart();
                        if (trimmed.StartsWith("- ") || trimmed.StartsWith("• ") || trimmed.StartsWith("* ") || trimmed.StartsWith("o "))
                        {
                            var prefixLen = pContent.Length - trimmed.Length + 2;
                            if (prefixLen > 0 && prefixLen <= pContent.Length)
                                pContent = pContent.Substring(prefixLen);
                        }
                    }
                    sb.Append("[");
                    AppendParagraphContent(sb, p, pContent, availableFonts);
                    sb.Append("]");
                }
                if (!string.IsNullOrEmpty(groupParamStr))
                {
                    sb.Append("]");
                }
            }
            else
            {
                // Bulleted list
                var marker = effectiveBulletChar ?? "•";
                var markerEscaped = FormatBulletMarker(EscapeTypstText(marker), paragraph.BulletColor);
                var listIndent = BuildListIndentParams(paragraph);
                
                if (!string.IsNullOrEmpty(groupParamStr))
                {
                    sb.Append(groupParamStr);
                    sb.Append("[");
                }
                sb.Append($"#list(marker: [{markerEscaped}]{listIndent})");

                for (int k = i; k <= groupEnd; k++)
                {
                    var p = paragraphs[k];
                    var pContent = p.Content;
                    // Strip literal bullets
                    if (!p.HasBullet && !string.IsNullOrEmpty(pContent))
                    {
                        var trimmed = pContent.TrimStart();
                        if (trimmed.StartsWith("- ") || trimmed.StartsWith("• ") || trimmed.StartsWith("* ") || trimmed.StartsWith("o "))
                        {
                            var prefixLen = pContent.Length - trimmed.Length + 2;
                            if (prefixLen > 0 && prefixLen <= pContent.Length)
                                pContent = pContent.Substring(prefixLen);
                        }
                    }
                    sb.Append("[");
                    AppendParagraphContent(sb, p, pContent, availableFonts);
                    sb.Append("]");
                }
                if (!string.IsNullOrEmpty(groupParamStr))
                {
                    sb.Append("]");
                }
            }

            // Emit space after last list item if present
            var listSpaceAfter = paragraphs[groupEnd].SpaceAfter;
            if (listSpaceAfter > 0.01)
            {
                sb.Append($"#v({FormatPt(listSpaceAfter.Value)})");
            }

            i = groupEnd + 1;
        }
    }

    private static string FormatBulletMarker(string escapedMarker, string? bulletColor)
    {
        // a:buClr / a:buClrTx supply an explicit glyph color; otherwise the marker
        // inherits the surrounding text color (OOXML default behavior).
        return string.IsNullOrEmpty(bulletColor)
            ? escapedMarker
            : $"#text(fill: rgb(\"{bulletColor}\"))[{escapedMarker}]";
    }

    private static string BuildListIndentParams(TypstParagraph paragraph)
    {
        var (markerPos, bodyIndent) = ComputeListIndents(paragraph);

        var parts = new List<string>();
        if (markerPos != null)
        {
            if (markerPos.Value > 0.01)
            {
                parts.Add($"indent: {FormatPt(markerPos.Value)}");
            }
            if (bodyIndent > 0.01)
            {
                parts.Add($"body-indent: {FormatPt(bodyIndent)}");
            }
        }
        // PowerPoint applies spcAft between every pair of items; Typst's list spacing
        // parameter is the exact analogue. tight: false is required — tight lists
        // ignore spacing and fall back to par.leading between items.
        if (paragraph.SpaceAfter > 0.01)
        {
            parts.Add("tight: false");
            parts.Add($"spacing: {FormatPt(paragraph.SpaceAfter.Value)}");
        }
        return parts.Count > 0 ? ", " + string.Join(", ", parts) : "";
    }

    /// <summary>
    /// Maps OOXML marL/indent to Typst list geometry. OOXML: marL = body text offset;
    /// indent (typically negative) = first-line/marker offset relative to marL, so the
    /// marker sits at marL+indent and the body at marL. Typst: indent = marker offset,
    /// body-indent = body offset relative to the marker.
    /// Returns (null, 0) when neither attribute is defined (keep Typst defaults).
    /// </summary>
    private static (double? MarkerPos, double BodyIndent) ComputeListIndents(TypstParagraph paragraph)
    {
        if (paragraph.MarginLeft == null && paragraph.Indent == null)
            return (null, 0);

        var markerPos = Math.Max(0, (paragraph.MarginLeft ?? 0) + (paragraph.Indent ?? 0));
        var bodyIndent = paragraph.MarginLeft.HasValue
            ? Math.Max(0, paragraph.MarginLeft.Value - markerPos)
            : Math.Abs(paragraph.Indent ?? 0);
        return (markerPos, bodyIndent);
    }

    private static string BuildEnumParams(int start, TypstParagraph paragraph)
    {
        var parts = new List<string>();
        if (start > 1)
        {
            parts.Add($"start: {start}");
        }

        var (markerPos, bodyIndent) = ComputeListIndents(paragraph);
        if (markerPos != null)
        {
            if (markerPos.Value > 0.01)
            {
                parts.Add($"indent: {FormatPt(markerPos.Value)}");
            }
            if (bodyIndent > 0.01)
            {
                parts.Add($"body-indent: {FormatPt(bodyIndent)}");
            }
        }
        if (paragraph.SpaceAfter > 0.01)
        {
            parts.Add("tight: false");
            parts.Add($"spacing: {FormatPt(paragraph.SpaceAfter.Value)}");
        }

        return parts.Count > 0 ? "(" + string.Join(", ", parts) + ")" : "";
    }

    private string BuildTextParameters(TypstTextFormatting fmt, HashSet<string> availableFonts)
    {
        var parameters = new List<string>();

        parameters.Add($"size: {FormatPt(fmt.FontSize)}");

        if (fmt.Bold)
            parameters.Add("weight: \"bold\"");

        if (fmt.Italic)
            parameters.Add("style: \"italic\"");

        if (!string.IsNullOrEmpty(fmt.Color) && fmt.Color != "#000000")
            parameters.Add($"fill: rgb(\"{fmt.Color}\")");

        var fontFamily = SubstituteUnavailableFont(ResolveThemeFont(fmt.FontFamily), availableFonts);
        if (!string.IsNullOrEmpty(fontFamily) && fontFamily != "Arial" && availableFonts.Contains(fontFamily))
        {
            parameters.Add($"font: {BuildFontChainValue(fontFamily)}");
        }

        return parameters.Count > 0 ? $"#text({string.Join(", ", parameters)})" : "";
    }

    /// <summary>
    /// Builds the per-run <c>font:</c> value as the resolved family followed by the
    /// global fallback chain (duplicates removed). A bare single-family value would
    /// replace Typst's whole font chain and fall through to the embedded serif
    /// fallback when the family is missing from the compiler's font set.
    /// </summary>
    private string BuildFontChainValue(string fontFamily)
    {
        var chain = new List<string> { fontFamily };
        foreach (var fallback in _globalFontFamilies)
        {
            if (!chain.Contains(fallback, StringComparer.OrdinalIgnoreCase))
            {
                chain.Add(fallback);
            }
        }

        return chain.Count == 1
            ? $"\"{chain[0]}\""
            : $"({string.Join(", ", chain.Select(f => $"\"{f}\""))})";
    }

    private static bool AreFormattingEqual(TypstTextFormatting a, TypstTextFormatting b)
    {
        return a.FontSize == b.FontSize
            && a.Bold == b.Bold
            && a.Italic == b.Italic
            && a.Color == b.Color
            && a.FontFamily == b.FontFamily
            && a.Caps == b.Caps;
    }

    private static bool AllRunsHaveSameFormatting(List<TypstTextRun> runs)
    {
        if (runs.Count <= 1) return true;

        var first = runs[0].Formatting;
        for (int i = 1; i < runs.Count; i++)
        {
            if (!AreFormattingEqual(first, runs[i].Formatting))
                return false;
        }
        return true;
    }

    private static bool AllNonLineBreakRunsHaveSameFormatting(List<TypstTextRun> runs)
    {
        var textRuns = runs.Where(run => !run.IsLineBreak).ToList();
        if (textRuns.Count <= 1) return true;

        var first = textRuns[0].Formatting;
        for (int i = 1; i < textRuns.Count; i++)
        {
            if (!AreFormattingEqual(first, textRuns[i].Formatting))
                return false;
        }

        return true;
    }

    private static TypstTextFormatting GetCollapsedRunFormatting(TypstParagraph paragraph)
    {
        return paragraph.Runs.FirstOrDefault(run => !run.IsLineBreak)?.Formatting ?? paragraph.Formatting;
    }

    /// <summary>
    /// Computes the formatting asserted by a list-group #text wrapper. Weight and
    /// italics may only be asserted at group level when EVERY text run in the group
    /// agrees: inner per-run #text wrappers emit weight/style only when set, and
    /// Typst inherits unset parameters from the enclosing context — so a wrapper
    /// taken from a bold lead-in run would otherwise leak bold onto the regular
    /// runs of mixed-formatting items (e.g. sales deck slide 3 body bullets).
    /// Size/fill/font stay on the collapsed first run to keep marker glyph metrics.
    /// </summary>
    private static TypstTextFormatting GetUniformGroupFormatting(
        List<TypstParagraph> paragraphs, int groupStart, int groupEnd, TypstTextFormatting firstFmt)
    {
        var bold = firstFmt.Bold;
        var italic = firstFmt.Italic;

        for (int k = groupStart; k <= groupEnd && (bold || italic); k++)
        {
            foreach (var run in paragraphs[k].Runs)
            {
                if (run.IsLineBreak)
                    continue;

                bold &= run.Formatting.Bold;
                italic &= run.Formatting.Italic;
            }
        }

        return bold == firstFmt.Bold && italic == firstFmt.Italic
            ? firstFmt
            : firstFmt with { Bold = bold, Italic = italic };
    }

    private TypstTextFormatting MergeRunWithParagraphDefaults(TypstTextFormatting paragraphDefault, Drawing.Run run, StyleResolver? styleResolver, bool requireExplicitOnOff = false)
    {
        var runProps = run.RunProperties;
        if (runProps == null) return paragraphDefault;

        var result = paragraphDefault;

        if (runProps.FontSize?.Value != null)
            result = result with { FontSize = runProps.FontSize.Value / 100.0 };

        var bold = GetOnOffValue(runProps, runProps.Bold, "b", requireExplicitOnOff);
        if (bold.HasValue)
            result = result with { Bold = bold.Value };

        var italic = GetOnOffValue(runProps, runProps.Italic, "i", requireExplicitOnOff);
        if (italic.HasValue)
            result = result with { Italic = italic.Value };

        if (runProps.Underline?.Value != null && runProps.Underline.Value != Drawing.TextUnderlineValues.None)
            result = result with { Underline = true };

        var color = ExtractRunColor(runProps, styleResolver);
        if (!string.IsNullOrEmpty(color))
            result = result with { Color = color };

        // Hyperlink runs render in the theme's hlink color — PowerPoint overrides
        // the explicit run fill ( 19's example.com link).
        if (runProps.Elements<Drawing.HyperlinkOnClick>().FirstOrDefault() != null)
        {
            var hlinkColor = styleResolver?.ResolveSchemeColor("hlink");
            if (!string.IsNullOrEmpty(hlinkColor))
                result = result with { Color = hlinkColor };
        }

        var latinFont = runProps.Elements<Drawing.LatinFont>().FirstOrDefault();
        if (latinFont?.Typeface != null)
        {
            var fontName = latinFont.Typeface.Value ?? "";
            if (fontName.EndsWith(" Bold", StringComparison.OrdinalIgnoreCase))
            {
                fontName = fontName.Substring(0, fontName.Length - 5);
                result = result with { Bold = true };
            }
            result = result with { FontFamily = fontName };
        }

        var caps = ExtractCapAttribute(runProps);
        if (caps != null)
            result = result with { Caps = caps };

        return result;
    }

    private static bool? GetOnOffValue(OpenXmlElement element, BooleanValue? value, string attributeName, bool requireExplicit)
        => requireExplicit ? GetExplicitOnOffAttribute(element, attributeName) : value?.Value;

    private static bool? GetExplicitOnOffAttribute(OpenXmlElement element, string attributeName)
    {
        var match = Regex.Match(element.OuterXml, $@"\s{Regex.Escape(attributeName)}=""([01]|true|false|on|off)""", RegexOptions.IgnoreCase);
        return match.Success ? ParseOnOff(match.Groups[1].Value) : null;
    }

    private static void TrimTrailingTabs(StringBuilder content, List<TypstTextRun> runs)
    {
        while (content.Length > 0 && content[^1] == '\t')
            content.Length--;

        for (int i = runs.Count - 1; i >= 0; i--)
        {
            var run = runs[i];
            if (run.IsLineBreak)
                break;

            var trimmed = run.Content.TrimEnd('\t');
            if (trimmed.Length == run.Content.Length)
                break;

            run.Content = trimmed;
            if (trimmed.Length > 0)
                break;
        }
    }

    private void AppendParagraphContent(StringBuilder sb, TypstParagraph paragraph, string? overrideContent, HashSet<string> availableFonts)
    {
        if (paragraph.Runs.Count <= 1 || AllNonLineBreakRunsHaveSameFormatting(paragraph.Runs))
        {
            var paramStr = BuildTextParameters(paragraph.Formatting, availableFonts);
            var content = overrideContent ?? paragraph.Content;
            var caps = paragraph.Formatting.Caps;

            if (!string.IsNullOrEmpty(paramStr))
            {
                sb.Append(paramStr);
                sb.Append("[");
                if (caps == "all")
                    sb.Append("#upper[");
                AppendEscapedContentWithBreaks(sb, content);
                if (caps == "all")
                    sb.Append("]");
                sb.Append("]");
            }
            else
            {
                if (caps == "all")
                    sb.Append("#upper[");
                AppendEscapedContentWithBreaks(sb, content);
                if (caps == "all")
                    sb.Append("]");
            }
        }
        else
        {
            foreach (var run in paragraph.Runs)
            {
                if (run.IsLineBreak)
                {
                    sb.Append(" #linebreak() ");
                    continue;
                }

                var paramStr = BuildTextParameters(run.Formatting, availableFonts);
                var escapedContent = EscapeTypstText(run.Content);
                var caps = run.Formatting.Caps;

                if (!string.IsNullOrEmpty(paramStr))
                {
                    sb.Append(paramStr);
                    sb.Append("[");
                    if (caps == "all")
                        sb.Append("#upper[");
                    sb.Append(escapedContent);
                    if (caps == "all")
                        sb.Append("]");
                    sb.Append("]");
                }
                else
                {
                    if (caps == "all")
                        sb.Append("#upper[");
                    sb.Append(escapedContent);
                    if (caps == "all")
                        sb.Append("]");
                }
            }
        }
    }

    private static void AppendEscapedContentWithBreaks(StringBuilder sb, string content)
    {
        if (string.IsNullOrEmpty(content))
            return;

        var parts = content.Split('\n');
        for (int p = 0; p < parts.Length; p++)
        {
            if (p > 0)
                sb.Append(" #linebreak() ");
            if (!string.IsNullOrEmpty(parts[p]))
                sb.Append(EscapeTypstText(parts[p]));
        }
    }

    private void AppendParagraphLeading(StringBuilder sb, TypstParagraph paragraph)
    {
        var leading = GetParagraphLeading(paragraph);
        if (leading > 0.01)
        {
            sb.Append($"#set par(leading: {FormatPt(leading)})\n");
        }
    }

    private double GetParagraphLeading(TypstParagraph paragraph)
    {
        var fmt = GetCollapsedRunFormatting(paragraph);
        var advance = GetTypstNaturalAdvance(fmt.FontFamily, fmt.FontSize);

        if (paragraph.LineSpacing is { } spacing)
        {
            // Percentage values (spcPct) multiply the paragraph's own effective font size —
            // the element-level default size is wrong for mixed-formatting paragraphs.
            var lineSpacingPts = spacing < 10 ? fmt.FontSize * spacing : spacing;

            // Typst's par.leading is added to its natural advance (the cap height),
            // while the a:lnSpc value is the target line pitch.
            return Math.Max(0, lineSpacingPts - advance);
        }

        // No explicit a:lnSpc: reconcile Typst's default pitch (cap height + 0.65em)
        // with PowerPoint single spacing (hhea line height, capped for inflated metrics).
        var defaultLeading = GetSingleSpacingLeading(fmt.FontFamily, fmt.FontSize, advance);
        return defaultLeading;
    }

    private double GetTypstParagraphLeading(TypstTextElement text)
    {
        var fmt = text.Formatting;
        var advance = GetTypstNaturalAdvance(fmt.FontFamily, fmt.FontSize);

        if (text.LineSpacing is { } spacing)
        {
            var lineSpacingPts = spacing < 10 ? fmt.FontSize * spacing : spacing;

            // Typst's par.leading is added to its natural advance (the cap height),
            // while the a:lnSpc value is the target line pitch.
            return Math.Max(0, lineSpacingPts - advance);
        }

        return GetSingleSpacingLeading(fmt.FontFamily, fmt.FontSize, advance);
    }

    /// <summary>
    /// Leading that makes Typst render PowerPoint-style single spacing for text without
    /// an explicit a:lnSpc: target pitch = the font's hhea line height (see
    /// <see cref="GetSingleSpacingFactor"/>), Typst pitch = cap height + leading.
    /// Returns 0 (keep Typst's 0.65em default) when the font's metrics are unknown or
    /// the computed leading is within 0.5pt of the default — no visible change then.
    /// </summary>
    private double GetSingleSpacingLeading(string fontFamily, double fontSize, double advance)
    {
        var family = ResolveThemeFont(fontFamily);
        var metrics = GetFontMetrics(family);
        if (metrics == null || metrics.UnitsPerEm <= 0 || metrics.CapHeight <= 0)
        {
            return 0;
        }

        var leading = fontSize * GetSingleSpacingFactor(family) - advance;
        return Math.Abs(leading - fontSize * 0.65) > 0.5 ? Math.Max(0, leading) : 0;
    }

    /// <summary>
    /// Typst's natural line advance for a font: the cap height (Typst's default
    /// top-edge is cap-height, bottom-edge is baseline). Falls back to the previous
    /// 0.65em estimate when metrics or the cap height are unavailable.
    /// </summary>
    private double GetTypstNaturalAdvance(string fontFamily, double fontSize)
    {
        var metrics = GetFontMetrics(ResolveThemeFont(fontFamily));
        if (metrics != null && metrics.UnitsPerEm > 0 && metrics.CapHeight > 0)
        {
            return metrics.CapHeight / (double)metrics.UnitsPerEm * fontSize;
        }

        return fontSize * 0.65;
    }

    private double GetTextMetricOffset(TypstTextElement text)
    {
        var fontFamily = text.Formatting.FontFamily ?? "Arial";
        var metrics = GetFontMetrics(fontFamily);
        if (metrics == null || metrics.UnitsPerEm <= 0)
            return 0;

        var scale = text.Formatting.FontSize / metrics.UnitsPerEm;
        var typoAscender = metrics.TypoAscender != 0 ? metrics.TypoAscender : metrics.HheaAscender;
        var renderAscender = metrics.WinAscent != 0 ? metrics.WinAscent : Math.Max(0, (int)metrics.HheaAscender);
        var ascenderDelta = Math.Max(0, renderAscender - typoAscender) * scale;

        return ascenderDelta;
    }

    private bool IsSingleLineAutoFit(TypstTextElement text, double height)
    {
        if (!text.AutoFit || text.ParagraphCount != 1 || text.HasExplicitLineBreaks)
            return false;

        var lineHeight = text.LineSpacing ?? text.Formatting.FontSize;
        return height <= lineHeight * 1.25;
    }

    private double? MeasureTextWidth(TypstTextElement text)
    {
        if (!TryGetFontMetrics(text, out var metrics) || metrics.UnitsPerEm <= 0 || metrics.AdvanceWidths.Count == 0)
            return null;

        var totalAdvance = 0L;
        foreach (var rune in text.Content.EnumerateRunes())
        {
            if (!metrics.AdvanceWidths.TryGetValue(rune.Value, out var advance))
                return null;

            totalAdvance += advance;
        }

        return totalAdvance * text.Formatting.FontSize / metrics.UnitsPerEm;
    }

    private void GenerateImageSource(StringBuilder sb, TypstImageElement image,
        string widthStr, string heightStr)
    {
        var relativePath = $"assets/{image.FileName}";

        // Image geometry comes from the PPTX frame. Native pixel dimensions are
        // retained on TypstImageElement for diagnostics but must not change layout.
        var imageTag = $"#image(\"{relativePath}\", width: {widthStr}, height: {heightStr})";

        // Wrap in a clipping block if corner radius is set. #rect has no clip
        // argument (compilation fails with "unexpected argument: clip"); #block
        // supports clip + radius and gives the same rounded-corner clip semantics.
        if (image.CornerRadius > 0)
        {
            var radius = FormatPt(image.CornerRadius);
            sb.Append($"#block(clip: true, width: {widthStr}, height: {heightStr}, radius: {radius})[{imageTag}]");
        }
        else
        {
            sb.Append(imageTag);
        }
    }

    private void GenerateShapeSource(StringBuilder sb, TypstShapeElement shape, string widthStr, string heightStr, double width, double height, double rotation = 0.0)
    {
        var fill = shape.FillGradient != null
            ? $"fill: {FormatGradient(shape.FillGradient)}"
            : !string.IsNullOrEmpty(shape.FillColor) ? $"fill: rgb(\"{shape.FillColor}\")" : "";
        var stroke = shape.StrokeWidth > 0 && !string.IsNullOrEmpty(shape.StrokeColor)
            ? $"stroke: {FormatPt(shape.StrokeWidth)} + rgb(\"{shape.StrokeColor}\")"
            // SmartArt-extracted shapes with no resolved stroke must suppress Typst's
            // default 1pt black stroke (PowerPoint "no border" semantics).
            : shape.NoStroke ? "stroke: none" : "";

        switch (shape.ShapeType)
        {
            case "rect":
                sb.Append($"#rect(width: {widthStr}, height: {heightStr}");
                if (!string.IsNullOrEmpty(fill)) sb.Append($", {fill}");
                if (!string.IsNullOrEmpty(stroke)) sb.Append($", {stroke}");
                if (shape.CornerRadius > 0) sb.Append($", radius: {FormatPt(shape.CornerRadius)}");
                sb.Append(")");
                break;
            case "ellipse":
                sb.Append($"#ellipse(width: {widthStr}, height: {heightStr}");
                if (!string.IsNullOrEmpty(fill)) sb.Append($", {fill}");
                if (!string.IsNullOrEmpty(stroke)) sb.Append($", {stroke}");
                sb.Append(")");
                break;
            case "polygon":
                // Typst rejects a leading empty argument ("#polygon(, ...)"), so the
                // first emitted argument must not be preceded by a comma. Shapes with
                // neither fill nor stroke (noFill decorators, unparsed gradient fills)
                // get an explicit fill: none — invisible, matching PowerPoint semantics.
                //
                // A #polygon's Typst bbox is its INK bbox, which can be smaller than
                // the shape box (blockArc bands, stripes). The outer
                // #rotate(origin: center) would then rotate about the ink center
                // instead of the shape-box center (xfrm@rot semantics), displacing
                // the shape — wrap rotated polygons in an explicit-size block.
                var wrapForRotation = Math.Abs(rotation) > 0.01;
                if (wrapForRotation)
                    sb.Append($"#block(width: {widthStr}, height: {heightStr})[");

                if (shape.Subpaths.Count > 1)
                {
                    // Multi-contour custGeom (ring, letter counters): a flat #polygon
                    // would fill the holes — emit an even-odd #curve with one
                    // move/line/close component chain per subpath.
                    sb.Append("#curve(fill-rule: \"even-odd\"");
                    if (!string.IsNullOrEmpty(fill)) sb.Append($", {fill}");
                    if (!string.IsNullOrEmpty(stroke)) sb.Append($", {stroke}");
                    if (string.IsNullOrEmpty(fill) && string.IsNullOrEmpty(stroke))
                        sb.Append(", fill: none");
                    foreach (var subpath in shape.Subpaths)
                    {
                        var firstPoint = true;
                        foreach (var (x, y) in subpath)
                        {
                            var px = FormatPt(x * width);  // Scale to element width
                            var py = FormatPt(y * height); // Scale to element height
                            sb.Append(firstPoint
                                ? $", curve.move(({px}, {py}))"
                                : $", curve.line(({px}, {py}))");
                            firstPoint = false;
                        }
                        sb.Append(", curve.close(mode: \"straight\")");
                    }
                    sb.Append(")");
                    if (wrapForRotation)
                        sb.Append("]");
                    break;
                }

                sb.Append("#polygon(");
                var hasPolygonArg = false;
                if (!string.IsNullOrEmpty(fill))
                {
                    sb.Append(fill);
                    hasPolygonArg = true;
                }
                if (!string.IsNullOrEmpty(stroke))
                {
                    if (hasPolygonArg) sb.Append(", ");
                    sb.Append(stroke);
                    hasPolygonArg = true;
                }
                if (!hasPolygonArg)
                {
                    sb.Append("fill: none");
                    hasPolygonArg = true;
                }
                foreach (var (x, y) in shape.Points)
                {
                    var px = FormatPt(x * width);  // Scale to element width
                    var py = FormatPt(y * height); // Scale to element height
                    sb.Append(hasPolygonArg ? $", ({px}, {py})" : $"({px}, {py})");
                    hasPolygonArg = true;
                }
                sb.Append(")");
                if (wrapForRotation)
                    sb.Append("]");
                break;
        }
    }

    private static string FormatGradient(TypstGradientFill gradient)
    {
        // Same emission shape as the generation pipeline's TypstEmitter:
        // gradient.linear((rgb("…"), 0%), (rgb("…"), 100%), angle: 115deg)
        //
        // Typst requires the stops to span 0%..100%, but OOXML stops may sit
        // strictly inside that range — PowerPoint flat-extends the edge colors
        // to the shape bounds. Pad the edges with the boundary colors so the
        // emission both compiles and matches PowerPoint semantics.
        var stops = new List<TypstGradientStop>(gradient.Stops);
        if (stops.Count > 0 && stops[0].Offset > 0)
        {
            stops.Insert(0, stops[0] with { Offset = 0 });
        }

        if (stops.Count > 0 && stops[^1].Offset < 1)
        {
            stops.Add(stops[^1] with { Offset = 1 });
        }

        var stopArgs = string.Join(", ", stops.Select(s =>
            $"(rgb(\"{s.Color}\"), {FormatNumber(s.Offset * 100)}%)"));
        return $"gradient.linear({stopArgs}, angle: {FormatNumber(gradient.Angle)}deg)";
    }

    private static string FormatNumber(double value)
        => value.ToString("0.##", CultureInfo.InvariantCulture);

    private void GenerateTableSource(StringBuilder sb, TypstTableElement table, string width, string height)
    {
        var cols = table.Rows.Count > 0 ? table.Rows[0].Count : 0;

        // Column widths
        var colWidths = table.ColumnWidths.Count > 0
            ? string.Join(", ", table.ColumnWidths.Select(w => FormatPt(w)))
            : string.Join(", ", Enumerable.Repeat("1fr", cols));

        var rowHeights = table.RowHeights.Count == table.Rows.Count && table.RowHeights.All(h => h > 0)
            ? string.Join(", ", table.RowHeights.Select(h => FormatPt(h)))
            : null;

        // Determine if we need per-cell border control
        bool hasComplexBorders = table.Rows.Any(row => row.Any(cell => HasExplicitCellBorderState(cell.StylePart)));

        if (hasComplexBorders)
        {
            // Emit table without global stroke, handle per-cell
            sb.Append($"#table(columns: ({colWidths}), ");
        }
        else
        {
            // Existing behavior
            sb.Append($"#table(columns: ({colWidths}), stroke: {FormatPt(table.BorderWidth)} + rgb(\"{table.BorderColor ?? "#000000"}\"), ");
        }

        if (rowHeights != null)
            sb.Append($"rows: ({rowHeights}), ");

        // Generate cells
        foreach (var row in table.Rows)
        {
            foreach (var cell in row)
            {
                var cellParams = new List<string>();

                if (cell.RowSpan > 1)
                    cellParams.Add($"rowspan: {cell.RowSpan}");
                if (cell.ColSpan > 1)
                    cellParams.Add($"colspan: {cell.ColSpan}");
                if (!string.IsNullOrEmpty(cell.BackgroundColor))
                    cellParams.Add($"fill: rgb(\"{cell.BackgroundColor}\")");
                var inset = BuildCellInset(cell.Insets);
                if (!string.IsNullOrEmpty(inset))
                    cellParams.Add($"inset: {inset}");
                if (cell.VerticalAlign == "center")
                    cellParams.Add("align: left + horizon");

                var cellStroke = BuildCellStroke(cell, table.BorderWidth, table.BorderColor);
                if (!string.IsNullOrEmpty(cellStroke))
                    cellParams.Add($"stroke: {cellStroke}");
                else if (hasComplexBorders)
                    cellParams.Add($"stroke: {BuildDefaultCellStroke(table.BorderWidth, table.BorderColor)}");

                if (cellParams.Count > 0)
                {
                    sb.Append($"table.cell({string.Join(", ", cellParams)})[");
                }
                else
                {
                    sb.Append("[");
                }

                // Cell content with formatting
                var fmt = cell.Formatting;
                var textParams = new List<string>();

                if (fmt.FontSize != 18.0)
                    textParams.Add($"size: {FormatPt(fmt.FontSize)}");
                if (fmt.Bold)
                    textParams.Add("weight: \"bold\"");
                if (fmt.Italic)
                    textParams.Add("style: \"italic\"");
                if (!string.IsNullOrEmpty(fmt.Color) && fmt.Color != "#000000")
                    textParams.Add($"fill: rgb(\"{fmt.Color}\")");

                if (cell.Paragraphs.Count > 0)
                {
                    AppendTableCellParagraphs(sb, cell);
                }
                else if (textParams.Count > 0)
                {
                    sb.Append($"#text({string.Join(", ", textParams)})[");
                    AppendEscapedContentWithBreaks(sb, cell.Content);
                    sb.Append("]");
                }
                else
                {
                    AppendEscapedContentWithBreaks(sb, cell.Content);
                }

                sb.Append("], ");
            }
        }

        sb.Append(")");
    }

    private void AppendTableCellParagraphs(StringBuilder sb, TypstTableCell cell)
    {
        for (int i = 0; i < cell.Paragraphs.Count; i++)
        {
            if (i > 0)
                sb.Append("\n\n");

            var paragraph = cell.Paragraphs[i];
            var align = paragraph.Formatting.Align;
            // "justify" is a par property, not a Typst alignment — skip the wrapper.
            var hasExplicitAlign = !string.IsNullOrEmpty(align) && align != "left" && align != "justify";
            if (hasExplicitAlign)
                sb.Append($"#align({align})[");

            AppendTableParagraphContent(sb, paragraph);

            if (hasExplicitAlign)
                sb.Append("]");
        }
    }

    private static void AppendTableParagraphContent(StringBuilder sb, TypstParagraph paragraph)
    {
        if (paragraph.Runs.Count <= 1 || AllRunsHaveSameFormatting(paragraph.Runs))
        {
            var textParams = BuildTableTextParameters(GetCollapsedRunFormatting(paragraph));
            if (textParams.Count > 0)
                sb.Append($"#text({string.Join(", ", textParams)})[");

            AppendEscapedContentWithBreaks(sb, paragraph.Content);

            if (textParams.Count > 0)
                sb.Append("]");

            return;
        }

        foreach (var run in paragraph.Runs)
        {
            if (run.IsLineBreak)
            {
                sb.Append(" #linebreak() ");
                continue;
            }

            var textParams = BuildTableTextParameters(run.Formatting);
            if (textParams.Count > 0)
                sb.Append($"#text({string.Join(", ", textParams)})[");

            sb.Append(EscapeTypstText(run.Content));

            if (textParams.Count > 0)
                sb.Append("]");
        }
    }

    private static List<string> BuildTableTextParameters(TypstTextFormatting fmt)
    {
        var textParams = new List<string>();

        if (fmt.FontSize != 18.0)
            textParams.Add($"size: {FormatPt(fmt.FontSize)}");
        if (fmt.Bold)
            textParams.Add("weight: \"bold\"");
        if (fmt.Italic)
            textParams.Add("style: \"italic\"");
        if (!string.IsNullOrEmpty(fmt.Color) && fmt.Color != "#000000")
            textParams.Add($"fill: rgb(\"{fmt.Color}\")");

        return textParams;
    }

    private static string? BuildCellStroke(TypstTableCell cell, double defaultWidth, string? defaultColor)
    {
        var parts = new List<string>();
        var sp = cell.StylePart;
        if (sp == null) return null;

        AddStrokeSide(parts, "top", sp.BorderTopState, sp.BorderTopWidth, sp.BorderTopColor, defaultWidth, defaultColor);
        AddStrokeSide(parts, "bottom", sp.BorderBottomState, sp.BorderBottomWidth, sp.BorderBottomColor, defaultWidth, defaultColor);
        AddStrokeSide(parts, "left", sp.BorderLeftState, sp.BorderLeftWidth, sp.BorderLeftColor, defaultWidth, defaultColor);
        AddStrokeSide(parts, "right", sp.BorderRightState, sp.BorderRightWidth, sp.BorderRightColor, defaultWidth, defaultColor);

        return parts.Count > 0 ? $"({string.Join(", ", parts)})" : null;
    }

    private static string BuildDefaultCellStroke(double defaultWidth, string? defaultColor)
    {
        var stroke = $"{FormatPt(defaultWidth)} + rgb(\"{defaultColor ?? "#000000"}\")";
        return $"(top: {stroke}, bottom: {stroke}, left: {stroke}, right: {stroke})";
    }

    private static bool HasExplicitCellBorderState(TableStylePart? stylePart)
    {
        if (stylePart == null) return false;

        return stylePart.BorderTopState is TableBorderState.Visible or TableBorderState.None
            || stylePart.BorderBottomState is TableBorderState.Visible or TableBorderState.None
            || stylePart.BorderLeftState is TableBorderState.Visible or TableBorderState.None
            || stylePart.BorderRightState is TableBorderState.Visible or TableBorderState.None;
    }

    private static void AddStrokeSide(List<string> parts, string side, TableBorderState state, double? width, string? color, double defaultWidth, string? defaultColor)
    {
        if (state == TableBorderState.None)
        {
            parts.Add($"{side}: none");
            return;
        }

        if (state == TableBorderState.Visible)
        {
            parts.Add($"{side}: {FormatPt(width ?? defaultWidth)} + rgb(\"{color ?? defaultColor ?? "#000000"}\")");
        }
    }

}
