using System.Globalization;
using System.IO.Compression;
using System.Text;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Presentation;
using Drawing = DocumentFormat.OpenXml.Drawing;
using P = DocumentFormat.OpenXml.Presentation;
using PptxEditor.Core.Models;

namespace PptxEditor.Core.Converters;

public sealed class PptxToTypstConverter : IDisposable
{
    private readonly PresentationDocument _document;
    private readonly string _tempDirectory;
    private readonly string _assetsDirectory;
    private readonly string _fontsDirectory;
    private readonly Dictionary<string, TypstFontMetrics> _fontMetrics = new(StringComparer.OrdinalIgnoreCase);
    private int _imageCounter;

    public PptxToTypstConverter(PresentationDocument document)
    {
        _document = document ?? throw new ArgumentNullException(nameof(document));
        _tempDirectory = Path.Combine(Path.GetTempPath(), "OfficeEditor", Guid.NewGuid().ToString("N"));
        _assetsDirectory = Path.Combine(_tempDirectory, "assets");
        _fontsDirectory = Path.Combine(_tempDirectory, "fonts");
        Directory.CreateDirectory(_assetsDirectory);
        Directory.CreateDirectory(_fontsDirectory);
    }

    public TypstPresentation Convert()
    {
        _fontMetrics.Clear();
        ExtractFonts();
        var fontFiles = Directory.GetFiles(_fontsDirectory).ToList();
        
        var presentation = new TypstPresentation
        {
            TempDirectory = _tempDirectory,
            FontFiles = fontFiles,
            FontMetrics = new Dictionary<string, TypstFontMetrics>(_fontMetrics, StringComparer.OrdinalIgnoreCase)
        };

        var slideIdList = _document.PresentationPart!.Presentation.SlideIdList;
        if (slideIdList == null) return presentation;

        int slideIndex = 1;
        foreach (var slideId in slideIdList.ChildElements.OfType<SlideId>())
        {
            var slidePart = (SlidePart)_document.PresentationPart.GetPartById(slideId.RelationshipId!);
            var slide = slidePart.Slide;
            if (slide == null) continue;

            var typstSlide = ConvertSlide(slidePart, slide, slideIndex);
            presentation.Slides.Add(typstSlide);
            slideIndex++;
        }

        return presentation;
    }

    public string GenerateTypstSource(TypstPresentation presentation)
    {
        var sb = new StringBuilder();
        
        // Header comment
        sb.AppendLine("// Generated by OfficeEditor from PPTX");
        sb.AppendLine();

        // Font setup with fallback chain
        // Extracted fonts will be loaded from the font-path directory
        var fontFamilies = new List<string> { "Arial", "Helvetica", "Liberation Sans" };
        
        var fontList = string.Join(", ", fontFamilies.Select(f => $"\"{f}\""));
        sb.AppendLine($"#set text(font: ({fontList}))");
        sb.AppendLine();

        // Process each slide
        for (int i = 0; i < presentation.Slides.Count; i++)
        {
            var slide = presentation.Slides[i];
            GenerateSlideSource(sb, slide, i == 0);
        }

        return sb.ToString();
    }

    private void GenerateSlideSource(StringBuilder sb, TypstSlide slide, bool isFirst)
    {
        // Page setup for this slide
        var width = slide.Layout.Width;
        var height = slide.Layout.Height;
        sb.AppendLine($"#set page(width: {FormatPt(width)}, height: {FormatPt(height)}, margin: 0pt)");

        // Background
        if (!string.IsNullOrEmpty(slide.Layout.BackgroundColor))
        {
            sb.AppendLine($"#set page(fill: rgb(\"{slide.Layout.BackgroundColor}\"))");
        }

        sb.AppendLine();

        // Page break before (except first)
        if (!isFirst)
        {
            sb.AppendLine("#pagebreak()");
            sb.AppendLine();
        }

        // Elements
        foreach (var element in slide.Elements)
        {
            GenerateElementSource(sb, element, slide.Layout.Width);
        }

        sb.AppendLine();
    }

    private void GenerateElementSource(StringBuilder sb, TypstElement element, double slideWidth)
    {
        var xPos = element.X;
        var yPos = element.Y;
        var width = element.Width;
        var height = element.Height;

        if (element.Type == "Text" && element.Text != null)
        {
            var text = element.Text;
            var topLeading = Math.Max(0, ((text.LineSpacing ?? text.Formatting.FontSize) - text.Formatting.FontSize) / 2);
            var metricOffset = GetTextMetricOffset(text);

            xPos += text.PaddingLeft;
            yPos += text.PaddingTop + topLeading + metricOffset;
            width = Math.Max(0, width - text.PaddingLeft - text.PaddingRight);
            height = Math.Max(0, height - text.PaddingTop - text.PaddingBottom);

            if (IsSingleLineAutoFit(text, height) && text.Formatting.Align == "left")
            {
                width = Math.Max(width, slideWidth - xPos - 2);
            }
        }

        var x = FormatPt(xPos);
        var y = FormatPt(yPos);
        var widthStr = FormatPt(width);
        var heightStr = FormatPt(height);

        sb.Append($"#place(top + left, dx: {x}, dy: {y})");
        sb.Append("[");

        switch (element.Type)
        {
            case "Text":
                GenerateTextSource(sb, element.Text!, widthStr);
                break;
            case "Image":
                GenerateImageSource(sb, element.Image!, widthStr, heightStr);
                break;
            case "Table":
                GenerateTableSource(sb, element.Table!, widthStr, heightStr);
                break;
            case "Shape":
                GenerateShapeSource(sb, element.Shape!, widthStr, heightStr, element.Width, element.Height);
                break;
        }

        sb.AppendLine("]");
    }

    private void GenerateTextSource(StringBuilder sb, TypstTextElement text, string width)
    {
        var fmt = text.Formatting;
        var parameters = new List<string>();

        parameters.Add($"size: {FormatPt(fmt.FontSize)}");
        
        if (fmt.Bold)
            parameters.Add("weight: \"bold\"");
        
        if (fmt.Italic)
            parameters.Add("style: \"italic\"");
        
        if (!string.IsNullOrEmpty(fmt.Color) && fmt.Color != "#000000")
            parameters.Add($"fill: rgb(\"{fmt.Color}\")");
        
        // Add font family if specified and not default
        if (!string.IsNullOrEmpty(fmt.FontFamily) && fmt.FontFamily != "Arial")
        {
            parameters.Add($"font: \"{fmt.FontFamily}\"");
        }

        // Constrain text to original text box width
        sb.Append($"#block(width: {width})[");

        var leading = GetTypstParagraphLeading(text);
        if (leading > 0.01)
        {
            sb.Append($"#set par(leading: {FormatPt(leading)})\n");
        }

        // Apply horizontal alignment if not left
        if (fmt.Align != "left" && !string.IsNullOrEmpty(fmt.Align))
        {
            sb.Append($"#align({fmt.Align})[");
        }

        var paramStr = parameters.Count > 0 ? $"#text({string.Join(", ", parameters)})" : "";
        
        AppendTextContent(sb, text, paramStr);

        // Close alignment wrapper if opened
        if (fmt.Align != "left" && !string.IsNullOrEmpty(fmt.Align))
        {
            sb.Append("]");
        }

        // Close block
        sb.Append("]");
    }

    private static void AppendTextContent(StringBuilder sb, TypstTextElement text, string paramStr)
    {
        var paragraphs = text.Content.Split("\n\n", StringSplitOptions.None);
        for (var i = 0; i < paragraphs.Length; i++)
        {
            if (i > 0 && !string.IsNullOrEmpty(paragraphs[i - 1]) && !string.IsNullOrEmpty(paragraphs[i]))
            {
                sb.Append("\n\n");
            }

            if (string.IsNullOrEmpty(paragraphs[i]))
            {
                sb.Append($"#v({FormatPt(text.LineSpacing ?? text.Formatting.FontSize)})\n");
                continue;
            }

            if (!string.IsNullOrEmpty(paramStr))
            {
                sb.Append(paramStr);
                sb.Append("[");
                sb.Append(EscapeTypstText(paragraphs[i]));
                sb.Append("]");
            }
            else
            {
                sb.Append(EscapeTypstText(paragraphs[i]));
            }
        }
    }

    private static double GetTypstParagraphLeading(TypstTextElement text)
    {
        if (text.LineSpacing == null)
            return 0;

        // Typst's par.leading is added to its own default line advance, while PPTX spcPts is the target line pitch.
        var estimatedTypstLineAdvance = text.Formatting.FontSize * 0.65;
        return Math.Max(0, text.LineSpacing.Value - estimatedTypstLineAdvance);
    }

    private double GetTextMetricOffset(TypstTextElement text)
    {
        if (!TryGetFontMetrics(text, out var metrics) || metrics.UnitsPerEm <= 0)
            return 0;

        var scale = text.Formatting.FontSize / metrics.UnitsPerEm;
        var typoAscender = metrics.TypoAscender != 0 ? metrics.TypoAscender : metrics.HheaAscender;
        var renderAscender = metrics.WinAscent != 0 ? metrics.WinAscent : Math.Max(0, (int)metrics.HheaAscender);
        var ascenderDelta = Math.Max(0, renderAscender - typoAscender) * scale;

        return ascenderDelta;
    }

    private bool IsSingleLineAutoFit(TypstTextElement text, double height)
    {
        if (!text.AutoFit || text.ParagraphCount != 1 || text.HasExplicitLineBreaks)
            return false;

        var lineHeight = text.LineSpacing ?? text.Formatting.FontSize;
        return height <= lineHeight * 1.25;
    }

    private double? MeasureTextWidth(TypstTextElement text)
    {
        if (!TryGetFontMetrics(text, out var metrics) || metrics.UnitsPerEm <= 0 || metrics.AdvanceWidths.Count == 0)
            return null;

        var totalAdvance = 0L;
        foreach (var rune in text.Content.EnumerateRunes())
        {
            if (!metrics.AdvanceWidths.TryGetValue(rune.Value, out var advance))
                return null;

            totalAdvance += advance;
        }

        return totalAdvance * text.Formatting.FontSize / metrics.UnitsPerEm;
    }

    private bool TryGetFontMetrics(TypstTextElement text, out TypstFontMetrics metrics)
    {
        if (text.Formatting.Bold && _fontMetrics.TryGetValue($"{text.Formatting.FontFamily} Bold", out var boldMetrics))
        {
            metrics = boldMetrics;
            return true;
        }

        if (_fontMetrics.TryGetValue(text.Formatting.FontFamily, out var familyMetrics))
        {
            metrics = familyMetrics;
            return true;
        }

        metrics = null!;
        return false;
    }

    private void GenerateImageSource(StringBuilder sb, TypstImageElement image, string width, string height)
    {
        var relativePath = $"assets/{image.FileName}";
        sb.Append($"#image(\"{relativePath}\", width: {width}, height: {height})");
    }

    private void GenerateShapeSource(StringBuilder sb, TypstShapeElement shape, string widthStr, string heightStr, double width, double height)
    {
        var fill = !string.IsNullOrEmpty(shape.FillColor) ? $"fill: rgb(\"{shape.FillColor}\")" : "";

        switch (shape.ShapeType)
        {
            case "rect":
                sb.Append($"#rect(width: {widthStr}, height: {heightStr}");
                if (!string.IsNullOrEmpty(fill)) sb.Append($", {fill}");
                if (shape.CornerRadius > 0) sb.Append($", radius: {FormatPt(shape.CornerRadius)}");
                sb.Append(")");
                break;
            case "ellipse":
                sb.Append($"#ellipse(width: {widthStr}, height: {heightStr}");
                if (!string.IsNullOrEmpty(fill)) sb.Append($", {fill}");
                sb.Append(")");
                break;
            case "polygon":
                if (!string.IsNullOrEmpty(fill))
                {
                    sb.Append($"#polygon({fill}");
                }
                else
                {
                    sb.Append("#polygon(");
                }
                foreach (var (x, y) in shape.Points)
                {
                    var px = FormatPt(x * width);  // Scale to element width
                    var py = FormatPt(y * height); // Scale to element height
                    sb.Append($", ({px}, {py})");
                }
                sb.Append(")");
                break;
        }
    }

    private void GenerateTableSource(StringBuilder sb, TypstTableElement table, string width, string height)
    {
        var cols = table.Rows.Count > 0 ? table.Rows[0].Count : 0;
        
        // Column widths
        var colWidths = table.ColumnWidths.Count > 0
            ? string.Join(", ", table.ColumnWidths.Select(w => FormatPt(w)))
            : string.Join(", ", Enumerable.Repeat("1fr", cols));

        sb.Append($"#table(columns: ({colWidths}), stroke: {FormatPt(table.BorderWidth)}pt + rgb(\"{table.BorderColor ?? "#000000"}\"), ");

        // Generate cells
        foreach (var row in table.Rows)
        {
            foreach (var cell in row)
            {
                var cellParams = new List<string>();
                
                if (cell.RowSpan > 1)
                    cellParams.Add($"rowspan: {cell.RowSpan}");
                if (cell.ColSpan > 1)
                    cellParams.Add($"colspan: {cell.ColSpan}");
                if (!string.IsNullOrEmpty(cell.BackgroundColor))
                    cellParams.Add($"fill: rgb(\"{cell.BackgroundColor}\")");

                if (cellParams.Count > 0)
                {
                    sb.Append($"table.cell({string.Join(", ", cellParams)})[");
                }
                else
                {
                    sb.Append("[");
                }

                // Cell content with formatting
                var fmt = cell.Formatting;
                var textParams = new List<string>();
                
                if (fmt.FontSize != 18.0)
                    textParams.Add($"size: {FormatPt(fmt.FontSize)}");
                if (fmt.Bold)
                    textParams.Add("weight: \"bold\"");
                if (fmt.Italic)
                    textParams.Add("style: \"italic\"");
                if (!string.IsNullOrEmpty(fmt.Color) && fmt.Color != "#000000")
                    textParams.Add($"fill: rgb(\"{fmt.Color}\")");

                if (textParams.Count > 0)
                {
                    sb.Append($"#text({string.Join(", ", textParams)})[");
                    sb.Append(EscapeTypstText(cell.Content));
                    sb.Append("]");
                }
                else
                {
                    sb.Append(EscapeTypstText(cell.Content));
                }

                sb.Append("], ");
            }
        }

        sb.Append(")");
    }

    private TypstSlide ConvertSlide(SlidePart slidePart, Slide slide, int slideIndex)
    {
        var styleResolver = new StyleResolver(_document, slidePart);
        var layout = ExtractSlideLayout(slidePart, slide, styleResolver);
        var typstSlide = new TypstSlide
        {
            SlideIndex = slideIndex,
            Layout = layout
        };

        var shapeTree = slide.CommonSlideData?.ShapeTree;
        if (shapeTree == null) return typstSlide;

        foreach (var element in shapeTree.ChildElements)
        {
            foreach (var typstElement in ConvertElement(slidePart, element, styleResolver))
            {
                typstSlide.Elements.Add(typstElement);
            }
        }

        return typstSlide;
    }

    private Models.SlideLayout ExtractSlideLayout(SlidePart slidePart, Slide slide, StyleResolver styleResolver)
    {
        // Default to 16:9 (960pt x 540pt at 96 DPI, or 10in x 5.625in = 720pt x 405pt)
        double width = 720;
        double height = 405;
        string? bgColor = null;

        // Try to get slide dimensions from presentation
        var presentation = _document.PresentationPart!.Presentation;
        var sldSz = presentation.SlideSize;
        if (sldSz != null)
        {
            width = EmuToPt(sldSz.Cx?.Value ?? 9144000);
            height = EmuToPt(sldSz.Cy?.Value ?? 6858000);
        }

        // Background - use style resolver for cascade: slide -> layout -> master
        bgColor = styleResolver.ResolveBackgroundColor();

        return new Models.SlideLayout
        {
            Width = width,
            Height = height,
            BackgroundColor = bgColor
        };
    }

    private IEnumerable<TypstElement> ConvertElement(SlidePart slidePart, OpenXmlElement element, StyleResolver styleResolver, double offX = 0, double offY = 0, double scaleX = 1, double scaleY = 1)
    {
        return element switch
        {
            P.Shape shape => ConvertShape(slidePart, shape, styleResolver, offX, offY, scaleX, scaleY),
            P.Picture picture => ConvertPicture(slidePart, picture, offX, offY, scaleX, scaleY),
            P.GraphicFrame graphicFrame => ConvertGraphicFrame(graphicFrame, offX, offY, scaleX, scaleY),
            P.GroupShape groupShape => ConvertGroupShape(slidePart, groupShape, styleResolver, offX, offY, scaleX, scaleY),
            _ => Array.Empty<TypstElement>()
        };
    }

    private IEnumerable<TypstElement> ConvertShape(SlidePart slidePart, P.Shape shape, StyleResolver styleResolver, double offX, double offY, double scaleX, double scaleY)
    {
        var (id, name) = GetElementIdAndName(shape.NonVisualShapeProperties);
        var position = GetElementPosition(shape.ShapeProperties);
        var text = ExtractTextFromShape(shape, styleResolver);

        // Apply group transform
        var finalX = offX + position.X * scaleX;
        var finalY = offY + position.Y * scaleY;
        var finalW = position.Width * scaleX;
        var finalH = position.Height * scaleY;

        // Check for image fill
        var blipFill = shape.ShapeProperties?.Elements<Drawing.BlipFill>().FirstOrDefault();
        if (blipFill != null)
        {
            var imageElement = ExtractImageFromBlipFill(slidePart, blipFill);
            if (imageElement != null)
            {
                // If shape also has text, we should ideally overlay it
                // For now, return image if no text, or prioritize text if present
                if (string.IsNullOrWhiteSpace(text.Content))
                {
                    yield return new TypstElement
                    {
                        Type = "Image",
                        Id = id,
                        Name = name,
                        X = finalX,
                        Y = finalY,
                        Width = finalW,
                        Height = finalH,
                        Image = imageElement
                    };
                    yield break;
                }
            }
        }

        // Check for shape geometry with fill
        var shapeElement = ExtractShapeGeometry(shape.ShapeProperties);
        if (shapeElement != null && !string.IsNullOrEmpty(shapeElement.FillColor))
        {
            // Return shape element
            yield return new TypstElement
            {
                Type = "Shape",
                Id = id,
                Name = name,
                X = finalX,
                Y = finalY,
                Width = finalW,
                Height = finalH,
                Shape = shapeElement
            };
        }

        // Return text if present
        if (!string.IsNullOrWhiteSpace(text.Content))
        {
            yield return new TypstElement
            {
                Type = "Text",
                Id = id,
                Name = name,
                X = finalX,
                Y = finalY,
                Width = finalW,
                Height = finalH,
                Text = text
            };
        }
    }

    private TypstShapeElement? ExtractShapeGeometry(ShapeProperties? shapeProperties)
    {
        if (shapeProperties == null) return null;

        // Extract fill color
        var fillColor = ExtractShapeFillColor(shapeProperties);

        // Check for preset geometry
        var prstGeom = shapeProperties.Elements<Drawing.PresetGeometry>().FirstOrDefault();
        if (prstGeom != null)
        {
            var prst = prstGeom.Preset?.Value;
            if (prst == Drawing.ShapeTypeValues.Rectangle || prst == Drawing.ShapeTypeValues.RoundRectangle)
            {
                return new TypstShapeElement
                {
                    ShapeType = "rect",
                    FillColor = fillColor,
                    CornerRadius = prst == Drawing.ShapeTypeValues.RoundRectangle ? 5.0 : 0
                };
            }
            if (prst == Drawing.ShapeTypeValues.Ellipse)
            {
                return new TypstShapeElement
                {
                    ShapeType = "ellipse",
                    FillColor = fillColor
                };
            }
        }

        // Check for custom geometry (path-based shapes)
        var custGeom = shapeProperties.Elements<Drawing.CustomGeometry>().FirstOrDefault();
        if (custGeom != null)
        {
            var pathList = custGeom.Elements<Drawing.PathList>().FirstOrDefault();
            if (pathList != null)
            {
                var path = pathList.Elements<Drawing.Path>().FirstOrDefault();
                if (path != null)
                {
                    var points = ExtractPathPoints(path);
                    if (points.Count > 2)
                    {
                        // Check if it's a simple rectangle (4 points + close)
                        if (IsRectanglePath(points))
                        {
                            return new TypstShapeElement
                            {
                                ShapeType = "rect",
                                FillColor = fillColor
                            };
                        }

                        // Otherwise treat as polygon
                        return new TypstShapeElement
                        {
                            ShapeType = "polygon",
                            FillColor = fillColor,
                            Points = points
                        };
                    }
                }
            }
        }

        // No recognizable geometry
        if (!string.IsNullOrEmpty(fillColor))
        {
            // Fallback: treat as rectangle with fill
            return new TypstShapeElement
            {
                ShapeType = "rect",
                FillColor = fillColor
            };
        }

        return null;
    }

    private string ExtractShapeFillColor(ShapeProperties shapeProperties)
    {
        var solidFill = shapeProperties.Elements<Drawing.SolidFill>().FirstOrDefault();
        if (solidFill != null)
        {
            var color = ExtractColor(solidFill);
            if (!string.IsNullOrEmpty(color))
            {
                return color;
            }
        }
        return string.Empty;
    }

    private List<(double X, double Y)> ExtractPathPoints(Drawing.Path path)
    {
        var points = new List<(double X, double Y)>();
        var width = (double)(path.Width?.Value ?? 1);
        var height = (double)(path.Height?.Value ?? 1);
        var currentX = 0.0;
        var currentY = 0.0;

        foreach (var cmd in path.ChildElements)
        {
            switch (cmd)
            {
                case Drawing.MoveTo moveTo:
                    (currentX, currentY) = GetPoint(moveTo.Point, width, height);
                    points.Add((currentX, currentY));
                    break;

                case Drawing.LineTo lineTo:
                    (currentX, currentY) = GetPoint(lineTo.Point, width, height);
                    points.Add((currentX, currentY));
                    break;

                case Drawing.CubicBezierCurveTo cubicBez:
                    // cubicBezTo contains 3 points: control1, control2, end
                    var bezPoints = cubicBez.Elements<Drawing.Point>().ToList();
                    if (bezPoints.Count >= 3)
                    {
                        var (c1x, c1y) = GetPoint(bezPoints[0], width, height);
                        var (c2x, c2y) = GetPoint(bezPoints[1], width, height);
                        var (ex, ey) = GetPoint(bezPoints[2], width, height);

                        // Sample 8 points along the bezier curve
                        for (int i = 1; i <= 8; i++)
                        {
                            double t = i / 9.0;
                            double mt = 1 - t;
                            double mt2 = mt * mt;
                            double mt3 = mt2 * mt;
                            double t2 = t * t;
                            double t3 = t2 * t;

                            double bx = mt3 * currentX + 3 * mt2 * t * c1x + 3 * mt * t2 * c2x + t3 * ex;
                            double by = mt3 * currentY + 3 * mt2 * t * c1y + 3 * mt * t2 * c2y + t3 * ey;
                            points.Add((bx, by));
                        }

                        currentX = ex;
                        currentY = ey;
                    }
                    break;

                case Drawing.CloseShapePath:
                    // Don't add duplicate close point
                    break;
            }
        }

        return points;
    }

    private (double X, double Y) GetPoint(Drawing.Point? point, double width, double height)
    {
        if (point == null) return (0, 0);
        var xStr = point.X?.Value ?? "0";
        var yStr = point.Y?.Value ?? "0";
        var x = double.TryParse(xStr, NumberStyles.Any, CultureInfo.InvariantCulture, out var xp) ? xp : 0;
        var y = double.TryParse(yStr, NumberStyles.Any, CultureInfo.InvariantCulture, out var yp) ? yp : 0;
        // Normalize to 0-1 range
        return (x / width, y / height);
    }

    private bool IsRectanglePath(List<(double X, double Y)> points)
    {
        if (points.Count < 4) return false;
        // Check if points form axis-aligned rectangle (with some tolerance)
        var distinctXs = points.Select(p => Math.Round(p.X, 3)).Distinct().ToList();
        var distinctYs = points.Select(p => Math.Round(p.Y, 3)).Distinct().ToList();
        return distinctXs.Count == 2 && distinctYs.Count == 2;
    }

    private IEnumerable<TypstElement> ConvertPicture(SlidePart slidePart, P.Picture picture, double offX, double offY, double scaleX, double scaleY)
    {
        var (id, name) = GetElementIdAndName(picture.NonVisualPictureProperties);
        var position = GetElementPosition(picture.ShapeProperties);

        var imageElement = ExtractImage(slidePart, picture);
        if (imageElement == null) yield break;

        yield return new TypstElement
        {
            Type = "Image",
            Id = id,
            Name = name,
            X = offX + position.X * scaleX,
            Y = offY + position.Y * scaleY,
            Width = position.Width * scaleX,
            Height = position.Height * scaleY,
            Image = imageElement
        };
    }

    private IEnumerable<TypstElement> ConvertGraphicFrame(P.GraphicFrame graphicFrame, double offX, double offY, double scaleX, double scaleY)
    {
        var (id, name) = GetElementIdAndName(graphicFrame.NonVisualGraphicFrameProperties);
        var position = GetGraphicFramePosition(graphicFrame);

        var graphicData = graphicFrame.Graphic?.GraphicData;
        if (graphicData == null) yield break;

        var table = graphicData.Elements<Drawing.Table>().FirstOrDefault();
        if (table != null)
        {
            var tableElement = ExtractTable(table);
            yield return new TypstElement
            {
                Type = "Table",
                Id = id,
                Name = name,
                X = offX + position.X * scaleX,
                Y = offY + position.Y * scaleY,
                Width = position.Width * scaleX,
                Height = position.Height * scaleY,
                Table = tableElement
            };
        }
    }

    private IEnumerable<TypstElement> ConvertGroupShape(SlidePart slidePart, P.GroupShape groupShape, StyleResolver styleResolver, double parentOffX, double parentOffY, double parentScaleX, double parentScaleY)
    {
        var grpXfrm = groupShape.GroupShapeProperties?.TransformGroup;

        double newOffX = parentOffX;
        double newOffY = parentOffY;
        double newScaleX = parentScaleX;
        double newScaleY = parentScaleY;

        if (grpXfrm != null)
        {
            var grpOffX = EmuToPt((long)(grpXfrm.Offset?.X?.Value ?? 0));
            var grpOffY = EmuToPt((long)(grpXfrm.Offset?.Y?.Value ?? 0));
            var grpExtX = (double)(grpXfrm.Extents?.Cx?.Value ?? 1);
            var grpExtY = (double)(grpXfrm.Extents?.Cy?.Value ?? 1);
            var chOffX = EmuToPt((long)(grpXfrm.ChildOffset?.X?.Value ?? 0));
            var chOffY = EmuToPt((long)(grpXfrm.ChildOffset?.Y?.Value ?? 0));
            var chExtX = (double)(grpXfrm.ChildExtents?.Cx?.Value ?? 1);
            var chExtY = (double)(grpXfrm.ChildExtents?.Cy?.Value ?? 1);

            var localScaleX = grpExtX / chExtX;
            var localScaleY = grpExtY / chExtY;

            newOffX = parentOffX + (grpOffX - chOffX) * parentScaleX;
            newOffY = parentOffY + (grpOffY - chOffY) * parentScaleY;
            newScaleX = parentScaleX * localScaleX;
            newScaleY = parentScaleY * localScaleY;
        }

        foreach (var child in groupShape.ChildElements)
        {
            foreach (var element in ConvertElement(slidePart, child, styleResolver, newOffX, newOffY, newScaleX, newScaleY))
                yield return element;
        }
    }

    private TypstTextElement ExtractTextFromShape(P.Shape shape, StyleResolver styleResolver)
    {
        var textBody = shape.TextBody;
        if (textBody == null)
        {
            return new TypstTextElement { Content = "" };
        }

        var paragraphTexts = new List<string>();
        TypstTextFormatting? formatting = null;
        string? align = null;
        double? lineSpacing = null;
        var paragraphCount = 0;
        var hasExplicitLineBreaks = false;

        // Extract body properties (padding, auto-fit, anchor)
        var bodyPr = textBody.Elements<Drawing.BodyProperties>().FirstOrDefault();
        var autoFit = bodyPr?.Elements<Drawing.ShapeAutoFit>().FirstOrDefault() != null;
        var vertAlign = "top";
        var anchorVal = bodyPr?.Anchor?.Value.ToString();
        if (anchorVal != null)
        {
            if (anchorVal.Contains("Center"))
                vertAlign = "center";
            else if (anchorVal.Contains("Bottom"))
                vertAlign = "bottom";
        }
        var padLeft = EmuToPt(bodyPr?.LeftInset?.Value ?? 0);
        var padTop = EmuToPt(bodyPr?.TopInset?.Value ?? 0);
        var padRight = EmuToPt(bodyPr?.RightInset?.Value ?? 0);
        var padBottom = EmuToPt(bodyPr?.BottomInset?.Value ?? 0);

        foreach (var paragraph in textBody.Elements<Drawing.Paragraph>())
        {
            paragraphCount++;

            // Extract alignment from first paragraph
            if (align == null)
            {
                align = ExtractParagraphAlignment(paragraph);
            }

            if (lineSpacing == null)
            {
                lineSpacing = ExtractParagraphLineSpacing(paragraph);
            }

            var paragraphText = new StringBuilder();
            foreach (var child in paragraph.ChildElements)
            {
                if (child is Drawing.Run run)
                {
                    if (run.Text?.Text != null)
                    {
                        paragraphText.Append(run.Text.Text);
                    }

                    // Extract formatting from first run
                    if (formatting == null)
                    {
                        formatting = ExtractTextFormatting(run);
                    }
                }

                if (child is Drawing.Break)
                {
                    paragraphText.Append('\n');
                    hasExplicitLineBreaks = true;
                }
            }

            paragraphTexts.Add(paragraphText.ToString());
        }

        // Get default text style from master based on placeholder type
        var placeholderType = GetPlaceholderType(shape);
        var defaultStyle = styleResolver.GetDefaultTextStyle(placeholderType);

        // Merge explicit formatting with defaults
        var fmt = formatting ?? new TypstTextFormatting();
        if (align != null)
        {
            fmt = fmt with { Align = align };
        }

        // Apply defaults for missing values
        if (fmt.FontSize == 18.0 && defaultStyle.FontSize.HasValue)
            fmt = fmt with { FontSize = defaultStyle.FontSize.Value };
        if (!fmt.Bold && defaultStyle.Bold.HasValue)
            fmt = fmt with { Bold = defaultStyle.Bold.Value };
        if (!fmt.Italic && defaultStyle.Italic.HasValue)
            fmt = fmt with { Italic = defaultStyle.Italic.Value };
        if (fmt.Color == "#000000" && !string.IsNullOrEmpty(defaultStyle.Color))
            fmt = fmt with { Color = defaultStyle.Color };
        if (fmt.FontFamily == "Arial" && !string.IsNullOrEmpty(defaultStyle.FontFamily))
            fmt = fmt with { FontFamily = defaultStyle.FontFamily };

        return new TypstTextElement
        {
            Content = string.Join("\n\n", paragraphTexts).Trim(),
            Formatting = fmt,
            AutoFit = autoFit,
            VerticalAlign = vertAlign,
            PaddingLeft = padLeft,
            PaddingTop = padTop,
            PaddingRight = padRight,
            PaddingBottom = padBottom,
            LineSpacing = lineSpacing,
            ParagraphCount = Math.Max(1, paragraphCount),
            HasExplicitLineBreaks = hasExplicitLineBreaks
        };
    }

    private static PlaceholderValues? GetPlaceholderType(P.Shape shape)
    {
        var nvSpPr = shape.NonVisualShapeProperties;
        if (nvSpPr == null) return null;

        var ph = nvSpPr.Elements<PlaceholderShape>().FirstOrDefault();
        if (ph == null) return null;

        return ph.Type?.Value;
    }

    private double? ExtractParagraphLineSpacing(Drawing.Paragraph paragraph)
    {
        var pPr = paragraph.Elements<Drawing.ParagraphProperties>().FirstOrDefault();
        var lnSpc = pPr?.ChildElements.FirstOrDefault(e => e.LocalName == "lnSpc");
        var spcPts = lnSpc?.ChildElements.FirstOrDefault(e => e.LocalName == "spcPts");
        if (spcPts == null) return null;

        var valAttr = spcPts.GetAttribute("val", "");
        return int.TryParse(valAttr.Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var value)
            ? value / 100.0
            : null;
    }

    private string? ExtractParagraphAlignment(Drawing.Paragraph paragraph)
    {
        // ParagraphProperties is an element, not a property, in Drawing namespace
        var pPr = paragraph.Elements<Drawing.ParagraphProperties>().FirstOrDefault();
        if (pPr == null) return null;

        // The OpenXML SDK doesn't always parse the algn attribute into Alignment property
        // Read the raw XML attribute directly
        var algnAttr = pPr.GetAttribute("algn", "");
        if (!string.IsNullOrEmpty(algnAttr.Value))
        {
            return algnAttr.Value switch
            {
                "ctr" => "center",
                "r" => "right",
                "just" => "left",  // Typst doesn't have 'justify', use left as fallback
                _ => "left"
            };
        }

        return null;
    }

    private TypstTextFormatting ExtractTextFormatting(Drawing.Run run)
    {
        var runProps = run.RunProperties;
        if (runProps == null) return new TypstTextFormatting();

        var fmt = new TypstTextFormatting();

        // Font size (in hundredths of a point)
        if (runProps.FontSize?.Value != null)
        {
            fmt = fmt with { FontSize = runProps.FontSize.Value / 100.0 };
        }

        // Bold
        if (runProps.Bold?.Value != null)
        {
            fmt = fmt with { Bold = runProps.Bold.Value };
        }

        // Italic
        if (runProps.Italic?.Value != null)
        {
            fmt = fmt with { Italic = runProps.Italic.Value };
        }

        // Underline
        if (runProps.Underline?.Value != null && runProps.Underline.Value != Drawing.TextUnderlineValues.None)
        {
            fmt = fmt with { Underline = true };
        }

        // Color
        var color = ExtractRunColor(runProps);
        if (!string.IsNullOrEmpty(color))
        {
            fmt = fmt with { Color = color };
        }

        // Font family - map common "Bold" suffix fonts to base family
        var latinFont = runProps.Elements<Drawing.LatinFont>().FirstOrDefault();
        if (latinFont?.Typeface != null)
        {
            var fontName = latinFont.Typeface.Value;
            // If font name ends with " Bold" and bold isn't set, set it
            if (fontName.EndsWith(" Bold", StringComparison.OrdinalIgnoreCase))
            {
                fontName = fontName.Substring(0, fontName.Length - 5);
                fmt = fmt with { Bold = true };
            }
            fmt = fmt with { FontFamily = fontName };
        }

        return fmt;
    }

    private string? ExtractRunColor(Drawing.RunProperties runProps)
    {
        var solidFill = runProps.Elements<Drawing.SolidFill>().FirstOrDefault();
        if (solidFill != null)
        {
            return ExtractColor(solidFill);
        }

        return null;
    }

    private string? ExtractColor(Drawing.SolidFill solidFill)
    {
        var rgb = solidFill.RgbColorModelHex;
        if (rgb?.Val != null)
        {
            return $"#{rgb.Val.Value}";
        }

        var schemeColor = solidFill.SchemeColor;
        if (schemeColor?.Val != null)
        {
            // Map scheme colors - for now return a default
            return "#000000";
        }

        return null;
    }

    private TypstImageElement? ExtractImage(SlidePart slidePart, P.Picture picture)
    {
        var blipFill = picture.BlipFill;
        if (blipFill == null) return null;

        var blip = blipFill.Blip;
        if (blip == null) return null;

        var embed = blip.Embed?.Value;
        if (string.IsNullOrEmpty(embed)) return null;

        var imagePart = slidePart.GetPartById(embed) as ImagePart;
        if (imagePart == null) return null;

        // Determine file extension
        var extension = imagePart.ContentType switch
        {
            "image/png" => "png",
            "image/jpeg" => "jpg",
            "image/gif" => "gif",
            "image/bmp" => "bmp",
            "image/tiff" => "tiff",
            "image/x-icon" => "ico",
            "image/svg+xml" => "svg",
            _ => "bin"
        };

        _imageCounter++;
        var fileName = $"image_{_imageCounter}.{extension}";
        var fullPath = Path.Combine(_assetsDirectory, fileName);

        // Save image data
        using (var stream = imagePart.GetStream())
        using (var fileStream = File.Create(fullPath))
        {
            stream.CopyTo(fileStream);
        }

        return new TypstImageElement
        {
            FileName = fileName,
            FullPath = fullPath,
            Width = 0, // Will be set from shape position
            Height = 0
        };
    }

    private TypstImageElement? ExtractImageFromBlipFill(SlidePart slidePart, Drawing.BlipFill blipFill)
    {
        var blip = blipFill.Blip;
        if (blip == null) return null;

        var embed = blip.Embed?.Value;
        if (string.IsNullOrEmpty(embed)) return null;

        var imagePart = slidePart.GetPartById(embed) as ImagePart;
        if (imagePart == null) return null;

        // Determine file extension
        var extension = imagePart.ContentType switch
        {
            "image/png" => "png",
            "image/jpeg" => "jpg",
            "image/gif" => "gif",
            "image/bmp" => "bmp",
            "image/tiff" => "tiff",
            "image/x-icon" => "ico",
            "image/svg+xml" => "svg",
            _ => "bin"
        };

        _imageCounter++;
        var fileName = $"image_{_imageCounter}.{extension}";
        var fullPath = Path.Combine(_assetsDirectory, fileName);

        // Save image data
        using (var stream = imagePart.GetStream())
        using (var fileStream = File.Create(fullPath))
        {
            stream.CopyTo(fileStream);
        }

        return new TypstImageElement
        {
            FileName = fileName,
            FullPath = fullPath,
            Width = 0,
            Height = 0
        };
    }

    private TypstTableElement ExtractTable(Drawing.Table table)
    {
        var rows = new List<List<TypstTableCell>>();
        var columnWidths = new List<double>();
        var rowHeights = new List<double>();

        // Extract column widths from table grid
        var tableGrid = table.TableGrid;
        if (tableGrid != null)
        {
            foreach (var gridCol in tableGrid.Elements<Drawing.GridColumn>())
            {
                var width = gridCol.Width?.Value ?? 0;
                columnWidths.Add(EmuToPt((long)width));
            }
        }

        foreach (var row in table.Elements<Drawing.TableRow>())
        {
            var rowHeight = row.Height?.Value ?? 0;
            rowHeights.Add(EmuToPt((long)rowHeight));

            var rowCells = new List<TypstTableCell>();
            foreach (var cell in row.Elements<Drawing.TableCell>())
            {
                var cellText = ExtractCellText(cell);
                var cellFormatting = ExtractCellFormatting(cell);
                var bgColor = ExtractCellBackground(cell);

                rowCells.Add(new TypstTableCell
                {
                    Content = cellText,
                    Formatting = cellFormatting,
                    BackgroundColor = bgColor
                });
            }
            rows.Add(rowCells);
        }

        // Extract border info from table properties
        var borderColor = "#000000";
        var borderWidth = 1.0;
        
        var tableProps = table.TableProperties;
        if (tableProps != null)
        {
            // Could extract more detailed border info here
        }

        return new TypstTableElement
        {
            Rows = rows,
            ColumnWidths = columnWidths,
            RowHeights = rowHeights,
            BorderColor = borderColor,
            BorderWidth = borderWidth
        };
    }

    private string ExtractCellText(Drawing.TableCell cell)
    {
        var sb = new StringBuilder();
        var textBody = cell.TextBody;
        if (textBody == null) return "";

        foreach (var paragraph in textBody.Elements<Drawing.Paragraph>())
        {
            foreach (var run in paragraph.Elements<Drawing.Run>())
            {
                if (run.Text?.Text != null)
                {
                    sb.Append(run.Text.Text);
                }
            }
        }

        return sb.ToString().Trim();
    }

    private TypstTextFormatting ExtractCellFormatting(Drawing.TableCell cell)
    {
        // Try to get formatting from first run
        var textBody = cell.TextBody;
        if (textBody == null) return new TypstTextFormatting();

        foreach (var paragraph in textBody.Elements<Drawing.Paragraph>())
        {
            foreach (var run in paragraph.Elements<Drawing.Run>())
            {
                return ExtractTextFormatting(run);
            }
        }

        return new TypstTextFormatting();
    }

    private string? ExtractCellBackground(Drawing.TableCell cell)
    {
        var cellProps = cell.TableCellProperties;
        if (cellProps == null) return null;

        var fill = cellProps.Elements<Drawing.SolidFill>().FirstOrDefault();
        if (fill != null)
        {
            return ExtractColor(fill);
        }

        return null;
    }

    private (double X, double Y, double Width, double Height) GetElementPosition(ShapeProperties? shapeProperties)
    {
        if (shapeProperties?.Transform2D == null)
            return (0, 0, 100, 50);

        var transform = shapeProperties.Transform2D;
        var x = transform.Offset?.X?.Value ?? 0;
        var y = transform.Offset?.Y?.Value ?? 0;
        var width = transform.Extents?.Cx?.Value ?? 100;
        var height = transform.Extents?.Cy?.Value ?? 50;

        return (EmuToPt((long)x), EmuToPt((long)y), EmuToPt((long)width), EmuToPt((long)height));
    }

    private (double X, double Y, double Width, double Height) GetGraphicFramePosition(P.GraphicFrame graphicFrame)
    {
        var transform = graphicFrame.Transform;
        if (transform == null)
            return (0, 0, 100, 50);

        var x = transform.Offset?.X?.Value ?? 0;
        var y = transform.Offset?.Y?.Value ?? 0;
        var width = transform.Extents?.Cx?.Value ?? 100;
        var height = transform.Extents?.Cy?.Value ?? 50;

        return (EmuToPt((long)x), EmuToPt((long)y), EmuToPt((long)width), EmuToPt((long)height));
    }

    private (uint Id, string Name) GetElementIdAndName(OpenXmlElement? nvProperties)
    {
        if (nvProperties == null) return (0, "Unknown");

        var cnvPr = nvProperties.ChildElements.FirstOrDefault(e => e.LocalName == "cNvPr");
        if (cnvPr == null) return (0, "Unknown");

        uint id = 0;
        var idAttr = cnvPr.GetAttribute("id", "");
        if (!string.IsNullOrEmpty(idAttr.Value) && uint.TryParse(idAttr.Value, out var parsedId))
        {
            id = parsedId;
        }

        var nameAttr = cnvPr.GetAttribute("name", "");
        var name = !string.IsNullOrEmpty(nameAttr.Value) ? nameAttr.Value : "Unknown";

        return (id, name);
    }

    private void ExtractFonts()
    {
        var fontPartIndex = 0;

        var embeddedFonts = _document.PresentationPart!.Presentation
            .Descendants()
            .Where(e => e.LocalName == "embeddedFont")
            .ToList();

        foreach (var embeddedFont in embeddedFonts)
        {
            var family = embeddedFont.ChildElements.FirstOrDefault(e => e.LocalName == "font")?.GetAttribute("typeface", "").Value;
            foreach (var fontReference in embeddedFont.ChildElements.Where(e => e.LocalName is "regular" or "bold" or "italic" or "boldItalic"))
            {
                var relationshipId = fontReference.GetAttribute("id", "http://schemas.openxmlformats.org/officeDocument/2006/relationships").Value;
                if (string.IsNullOrEmpty(relationshipId)) continue;

                if (_document.PresentationPart.GetPartById(relationshipId) is FontPart fontPart)
                {
                    ExtractFontFile(fontPart, fontPartIndex, family);
                    fontPartIndex++;
                }
            }
        }

        if (fontPartIndex > 0)
            return;

        // Extract fonts from all parts
        var allParts = new List<OpenXmlPart>();
        allParts.Add(_document.PresentationPart!);
        allParts.AddRange(_document.PresentationPart!.SlideParts);
        
        foreach (var part in allParts)
        {
            foreach (var p in part.Parts)
            {
                if (p.OpenXmlPart is FontPart fontPart)
                {
                    ExtractFontFile(fontPart, fontPartIndex, family: null);
                    fontPartIndex++;
                }
            }
        }
    }

    private void ExtractFontFile(FontPart fontPart, int index, string? family)
    {
        using var stream = fontPart.GetStream();
        using var ms = new MemoryStream();
        stream.CopyTo(ms);
        var data = ms.ToArray();
        
        // Try to extract actual font from EOT wrapper
        var otfPos = data.AsSpan().IndexOf(System.Text.Encoding.ASCII.GetBytes("OTTO"));
        var ttfPos = data.AsSpan().IndexOf(new byte[] { 0x00, 0x01, 0x00, 0x00 });
        
        int pos;
        string ext;
        if (otfPos >= 0)
        {
            pos = otfPos;
            ext = ".otf";
        }
        else if (ttfPos >= 0)
        {
            pos = ttfPos;
            ext = ".ttf";
        }
        else
        {
            // Can't extract, save as-is
            var fileName = $"font{index}.fntdata";
            File.WriteAllBytes(Path.Combine(_fontsDirectory, fileName), data);
            return;
        }
        
        var fontDataLength = TryReadEotFontDataLength(data, pos);
        var fontData = data[pos..(pos + fontDataLength)];
        var fontName = $"font{index}{ext}";
        File.WriteAllBytes(Path.Combine(_fontsDirectory, fontName), fontData);

        var metrics = OpenTypeFontMetricsReader.TryRead(fontData);
        if (metrics != null && !string.IsNullOrWhiteSpace(family))
        {
            _fontMetrics[family] = metrics;
            if (family.EndsWith(" Bold", StringComparison.OrdinalIgnoreCase))
            {
                _fontMetrics.TryAdd(family[..^5], metrics);
            }
        }
    }

    private static int TryReadEotFontDataLength(byte[] data, int fontDataOffset)
    {
        if (data.Length >= 8)
        {
            var fontDataLength = BitConverter.ToUInt32(data, 4);
            if (fontDataLength > 0 && fontDataLength <= int.MaxValue && fontDataOffset + fontDataLength <= data.Length)
                return (int)fontDataLength;
        }

        return data.Length - fontDataOffset;
    }

    private static double EmuToPt(long emu)
    {
        return emu / 12700.0;
    }

    private static string FormatPt(double pt)
    {
        return pt.ToString("F2", CultureInfo.InvariantCulture) + "pt";
    }

    private static string EscapeTypstText(string text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        
        return text
            .Replace("\\", "\\\\")
            .Replace("[", "\\[")
            .Replace("]", "\\]")
            .Replace("*", "\\*")
            .Replace("_", "\\_")
            .Replace("#", "\\#")
            .Replace("`", "\\`");
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDirectory))
            {
                Directory.Delete(_tempDirectory, true);
            }
        }
        catch
        {
            // Best effort cleanup
        }
    }
}
