using System.Globalization;
using System.IO.Compression;
using System.Text;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Presentation;
using Drawing = DocumentFormat.OpenXml.Drawing;
using P = DocumentFormat.OpenXml.Presentation;
using PptxEditor.Core.Models;

namespace PptxEditor.Core.Converters;

public sealed class PptxToTypstConverter : IDisposable
{
    private readonly PresentationDocument _document;
    private readonly string _tempDirectory;
    private readonly string _assetsDirectory;
    private readonly string _fontsDirectory;
    private int _imageCounter;

    public PptxToTypstConverter(PresentationDocument document)
    {
        _document = document ?? throw new ArgumentNullException(nameof(document));
        _tempDirectory = Path.Combine(Path.GetTempPath(), "OfficeEditor", Guid.NewGuid().ToString("N"));
        _assetsDirectory = Path.Combine(_tempDirectory, "assets");
        _fontsDirectory = Path.Combine(_tempDirectory, "fonts");
        Directory.CreateDirectory(_assetsDirectory);
        Directory.CreateDirectory(_fontsDirectory);
    }

    public TypstPresentation Convert()
    {
        ExtractFonts();
        var fontFiles = Directory.GetFiles(_fontsDirectory).ToList();
        
        var presentation = new TypstPresentation
        {
            TempDirectory = _tempDirectory,
            FontFiles = fontFiles
        };

        var slideIdList = _document.PresentationPart!.Presentation.SlideIdList;
        if (slideIdList == null) return presentation;

        int slideIndex = 1;
        foreach (var slideId in slideIdList.ChildElements.OfType<SlideId>())
        {
            var slidePart = (SlidePart)_document.PresentationPart.GetPartById(slideId.RelationshipId!);
            var slide = slidePart.Slide;
            if (slide == null) continue;

            var typstSlide = ConvertSlide(slidePart, slide, slideIndex);
            presentation.Slides.Add(typstSlide);
            slideIndex++;
        }

        return presentation;
    }

    public string GenerateTypstSource(TypstPresentation presentation)
    {
        var sb = new StringBuilder();
        
        // Header comment
        sb.AppendLine("// Generated by OfficeEditor from PPTX");
        sb.AppendLine();

        // Font setup with fallback chain
        var fontFamilies = new List<string> { "Arial", "Helvetica", "Liberation Sans" };
        if (presentation.FontFiles.Count > 0)
        {
            // Add extracted font families at the beginning
            foreach (var fontFile in presentation.FontFiles)
            {
                var fontName = Path.GetFileNameWithoutExtension(fontFile);
                if (!fontFamilies.Contains(fontName))
                {
                    fontFamilies.Insert(0, fontName);
                }
            }
        }
        
        var fontList = string.Join(", ", fontFamilies.Select(f => $"\"{f}\""));
        sb.AppendLine($"#set text(font: ({fontList}))");
        sb.AppendLine();

        // Process each slide
        for (int i = 0; i < presentation.Slides.Count; i++)
        {
            var slide = presentation.Slides[i];
            GenerateSlideSource(sb, slide, i == 0);
        }

        return sb.ToString();
    }

    private void GenerateSlideSource(StringBuilder sb, TypstSlide slide, bool isFirst)
    {
        // Page setup for this slide
        var width = slide.Layout.Width;
        var height = slide.Layout.Height;
        sb.AppendLine($"#set page(width: {FormatPt(width)}, height: {FormatPt(height)}, margin: 0pt)");

        // Background
        if (!string.IsNullOrEmpty(slide.Layout.BackgroundColor))
        {
            sb.AppendLine($"#set page(fill: rgb(\"{slide.Layout.BackgroundColor}\"))");
        }

        sb.AppendLine();

        // Page break before (except first)
        if (!isFirst)
        {
            sb.AppendLine("#pagebreak(to: \"odd\")");
            sb.AppendLine();
        }

        // Elements
        foreach (var element in slide.Elements)
        {
            GenerateElementSource(sb, element);
        }

        sb.AppendLine();
    }

    private void GenerateElementSource(StringBuilder sb, TypstElement element)
    {
        var x = FormatPt(element.X);
        var y = FormatPt(element.Y);
        var width = FormatPt(element.Width);
        var height = FormatPt(element.Height);

        sb.Append($"#place(top + left, dx: {x}, dy: {y})");
        sb.Append("[");

        switch (element.Type)
        {
            case "Text":
                GenerateTextSource(sb, element.Text!, width);
                break;
            case "Image":
                GenerateImageSource(sb, element.Image!, width, height);
                break;
            case "Table":
                GenerateTableSource(sb, element.Table!, width, height);
                break;
        }

        sb.AppendLine("]");
    }

    private void GenerateTextSource(StringBuilder sb, TypstTextElement text, string width)
    {
        var fmt = text.Formatting;
        var parameters = new List<string>();

        parameters.Add($"size: {FormatPt(fmt.FontSize)}");
        
        if (fmt.Bold)
            parameters.Add("weight: \"bold\"");
        
        if (fmt.Italic)
            parameters.Add("style: \"italic\"");
        
        if (!string.IsNullOrEmpty(fmt.Color) && fmt.Color != "#000000")
            parameters.Add($"fill: rgb(\"{fmt.Color}\")");

        var paramStr = parameters.Count > 0 ? $"#text({string.Join(", ", parameters)})" : "";
        
        if (!string.IsNullOrEmpty(paramStr))
        {
            sb.Append(paramStr);
            sb.Append("[");
            sb.Append(EscapeTypstText(text.Content));
            sb.Append("]");
        }
        else
        {
            sb.Append(EscapeTypstText(text.Content));
        }
    }

    private void GenerateImageSource(StringBuilder sb, TypstImageElement image, string width, string height)
    {
        var relativePath = $"assets/{image.FileName}";
        sb.Append($"#image(\"{relativePath}\", width: {width}, height: {height})");
    }

    private void GenerateTableSource(StringBuilder sb, TypstTableElement table, string width, string height)
    {
        var cols = table.Rows.Count > 0 ? table.Rows[0].Count : 0;
        
        // Column widths
        var colWidths = table.ColumnWidths.Count > 0
            ? string.Join(", ", table.ColumnWidths.Select(w => FormatPt(w)))
            : string.Join(", ", Enumerable.Repeat("1fr", cols));

        sb.Append($"#table(columns: ({colWidths}), stroke: {FormatPt(table.BorderWidth)}pt + rgb(\"{table.BorderColor ?? "#000000"}\"), ");

        // Generate cells
        foreach (var row in table.Rows)
        {
            foreach (var cell in row)
            {
                var cellParams = new List<string>();
                
                if (cell.RowSpan > 1)
                    cellParams.Add($"rowspan: {cell.RowSpan}");
                if (cell.ColSpan > 1)
                    cellParams.Add($"colspan: {cell.ColSpan}");
                if (!string.IsNullOrEmpty(cell.BackgroundColor))
                    cellParams.Add($"fill: rgb(\"{cell.BackgroundColor}\")");

                if (cellParams.Count > 0)
                {
                    sb.Append($"table.cell({string.Join(", ", cellParams)})[");
                }
                else
                {
                    sb.Append("[");
                }

                // Cell content with formatting
                var fmt = cell.Formatting;
                var textParams = new List<string>();
                
                if (fmt.FontSize != 18.0)
                    textParams.Add($"size: {FormatPt(fmt.FontSize)}");
                if (fmt.Bold)
                    textParams.Add("weight: \"bold\"");
                if (fmt.Italic)
                    textParams.Add("style: \"italic\"");
                if (!string.IsNullOrEmpty(fmt.Color) && fmt.Color != "#000000")
                    textParams.Add($"fill: rgb(\"{fmt.Color}\")");

                if (textParams.Count > 0)
                {
                    sb.Append($"#text({string.Join(", ", textParams)})[");
                    sb.Append(EscapeTypstText(cell.Content));
                    sb.Append("]");
                }
                else
                {
                    sb.Append(EscapeTypstText(cell.Content));
                }

                sb.Append("], ");
            }
        }

        sb.Append(")");
    }

    private TypstSlide ConvertSlide(SlidePart slidePart, Slide slide, int slideIndex)
    {
        var layout = ExtractSlideLayout(slidePart, slide);
        var typstSlide = new TypstSlide
        {
            SlideIndex = slideIndex,
            Layout = layout
        };

        var shapeTree = slide.CommonSlideData?.ShapeTree;
        if (shapeTree == null) return typstSlide;

        foreach (var element in shapeTree.ChildElements)
        {
            var typstElement = ConvertElement(slidePart, element);
            if (typstElement != null)
            {
                typstSlide.Elements.Add(typstElement);
            }
        }

        return typstSlide;
    }

    private Models.SlideLayout ExtractSlideLayout(SlidePart slidePart, Slide slide)
    {
        // Default to 16:9 (960pt x 540pt at 96 DPI, or 10in x 5.625in = 720pt x 405pt)
        double width = 720;
        double height = 405;
        string? bgColor = null;

        // Try to get slide dimensions from presentation
        var presentation = _document.PresentationPart!.Presentation;
        var sldSz = presentation.SlideSize;
        if (sldSz != null)
        {
            width = EmuToPt(sldSz.Cx?.Value ?? 9144000);
            height = EmuToPt(sldSz.Cy?.Value ?? 6858000);
        }

        // Background
        var bg = slide.CommonSlideData?.Background;
        if (bg?.BackgroundProperties != null)
        {
            var bgProps = bg.BackgroundProperties;
            var solidFill = bgProps.Elements<Drawing.SolidFill>().FirstOrDefault();
            if (solidFill != null)
            {
                bgColor = ExtractColor(solidFill);
            }
        }

        return new Models.SlideLayout
        {
            Width = width,
            Height = height,
            BackgroundColor = bgColor
        };
    }

    private TypstElement? ConvertElement(SlidePart slidePart, OpenXmlElement element)
    {
        return element switch
        {
            P.Shape shape => ConvertShape(shape),
            P.Picture picture => ConvertPicture(slidePart, picture),
            P.GraphicFrame graphicFrame => ConvertGraphicFrame(graphicFrame),
            _ => null
        };
    }

    private TypstElement ConvertShape(P.Shape shape)
    {
        var (id, name) = GetElementIdAndName(shape.NonVisualShapeProperties);
        var position = GetElementPosition(shape.ShapeProperties);
        var text = ExtractTextFromShape(shape);

        return new TypstElement
        {
            Type = "Text",
            Id = id,
            Name = name,
            X = position.X,
            Y = position.Y,
            Width = position.Width,
            Height = position.Height,
            Text = text
        };
    }

    private TypstElement? ConvertPicture(SlidePart slidePart, P.Picture picture)
    {
        var (id, name) = GetElementIdAndName(picture.NonVisualPictureProperties);
        var position = GetElementPosition(picture.ShapeProperties);
        
        // Extract image
        var imageElement = ExtractImage(slidePart, picture);
        if (imageElement == null) return null;

        return new TypstElement
        {
            Type = "Image",
            Id = id,
            Name = name,
            X = position.X,
            Y = position.Y,
            Width = position.Width,
            Height = position.Height,
            Image = imageElement
        };
    }

    private TypstElement? ConvertGraphicFrame(P.GraphicFrame graphicFrame)
    {
        var (id, name) = GetElementIdAndName(graphicFrame.NonVisualGraphicFrameProperties);
        var position = GetGraphicFramePosition(graphicFrame);
        
        var graphicData = graphicFrame.Graphic?.GraphicData;
        if (graphicData == null) return null;

        var table = graphicData.Elements<Drawing.Table>().FirstOrDefault();
        if (table != null)
        {
            var tableElement = ExtractTable(table);
            return new TypstElement
            {
                Type = "Table",
                Id = id,
                Name = name,
                X = position.X,
                Y = position.Y,
                Width = position.Width,
                Height = position.Height,
                Table = tableElement
            };
        }

        return null;
    }

    private TypstTextElement ExtractTextFromShape(P.Shape shape)
    {
        var textBody = shape.TextBody;
        if (textBody == null)
        {
            return new TypstTextElement { Content = "" };
        }

        var sb = new StringBuilder();
        TypstTextFormatting? formatting = null;

        foreach (var paragraph in textBody.Elements<Drawing.Paragraph>())
        {
            foreach (var run in paragraph.Elements<Drawing.Run>())
            {
                if (run.Text?.Text != null)
                {
                    sb.Append(run.Text.Text);
                    
                    // Extract formatting from first run
                    if (formatting == null)
                    {
                        formatting = ExtractTextFormatting(run);
                    }
                }
            }
            sb.Append(" ");
        }

        return new TypstTextElement
        {
            Content = sb.ToString().Trim(),
            Formatting = formatting ?? new TypstTextFormatting()
        };
    }

    private TypstTextFormatting ExtractTextFormatting(Drawing.Run run)
    {
        var runProps = run.RunProperties;
        if (runProps == null) return new TypstTextFormatting();

        var fmt = new TypstTextFormatting();

        // Font size (in hundredths of a point)
        if (runProps.FontSize?.Value != null)
        {
            fmt = fmt with { FontSize = runProps.FontSize.Value / 100.0 };
        }

        // Bold
        if (runProps.Bold?.Value != null)
        {
            fmt = fmt with { Bold = runProps.Bold.Value };
        }

        // Italic
        if (runProps.Italic?.Value != null)
        {
            fmt = fmt with { Italic = runProps.Italic.Value };
        }

        // Underline
        if (runProps.Underline?.Value != null && runProps.Underline.Value != Drawing.TextUnderlineValues.None)
        {
            fmt = fmt with { Underline = true };
        }

        // Color
        var color = ExtractRunColor(runProps);
        if (!string.IsNullOrEmpty(color))
        {
            fmt = fmt with { Color = color };
        }

        // Font family
        var latinFont = runProps.Elements<Drawing.LatinFont>().FirstOrDefault();
        if (latinFont?.Typeface != null)
        {
            fmt = fmt with { FontFamily = latinFont.Typeface.Value };
        }

        return fmt;
    }

    private string? ExtractRunColor(Drawing.RunProperties runProps)
    {
        var solidFill = runProps.Elements<Drawing.SolidFill>().FirstOrDefault();
        if (solidFill != null)
        {
            return ExtractColor(solidFill);
        }

        return null;
    }

    private string? ExtractColor(Drawing.SolidFill solidFill)
    {
        var rgb = solidFill.RgbColorModelHex;
        if (rgb?.Val != null)
        {
            return $"#{rgb.Val.Value}";
        }

        var schemeColor = solidFill.SchemeColor;
        if (schemeColor?.Val != null)
        {
            // Map scheme colors - for now return a default
            return "#000000";
        }

        return null;
    }

    private TypstImageElement? ExtractImage(SlidePart slidePart, P.Picture picture)
    {
        var blipFill = picture.BlipFill;
        if (blipFill == null) return null;

        var blip = blipFill.Blip;
        if (blip == null) return null;

        var embed = blip.Embed?.Value;
        if (string.IsNullOrEmpty(embed)) return null;

        var imagePart = slidePart.GetPartById(embed) as ImagePart;
        if (imagePart == null) return null;

        // Determine file extension
        var extension = imagePart.ContentType switch
        {
            "image/png" => "png",
            "image/jpeg" => "jpg",
            "image/gif" => "gif",
            "image/bmp" => "bmp",
            "image/tiff" => "tiff",
            "image/x-icon" => "ico",
            "image/svg+xml" => "svg",
            _ => "bin"
        };

        _imageCounter++;
        var fileName = $"image_{_imageCounter}.{extension}";
        var fullPath = Path.Combine(_assetsDirectory, fileName);

        // Save image data
        using (var stream = imagePart.GetStream())
        using (var fileStream = File.Create(fullPath))
        {
            stream.CopyTo(fileStream);
        }

        return new TypstImageElement
        {
            FileName = fileName,
            FullPath = fullPath,
            Width = 0, // Will be set from shape position
            Height = 0
        };
    }

    private TypstTableElement ExtractTable(Drawing.Table table)
    {
        var rows = new List<List<TypstTableCell>>();
        var columnWidths = new List<double>();
        var rowHeights = new List<double>();

        // Extract column widths from table grid
        var tableGrid = table.TableGrid;
        if (tableGrid != null)
        {
            foreach (var gridCol in tableGrid.Elements<Drawing.GridColumn>())
            {
                var width = gridCol.Width?.Value ?? 0;
                columnWidths.Add(EmuToPt((long)width));
            }
        }

        foreach (var row in table.Elements<Drawing.TableRow>())
        {
            var rowHeight = row.Height?.Value ?? 0;
            rowHeights.Add(EmuToPt((long)rowHeight));

            var rowCells = new List<TypstTableCell>();
            foreach (var cell in row.Elements<Drawing.TableCell>())
            {
                var cellText = ExtractCellText(cell);
                var cellFormatting = ExtractCellFormatting(cell);
                var bgColor = ExtractCellBackground(cell);

                rowCells.Add(new TypstTableCell
                {
                    Content = cellText,
                    Formatting = cellFormatting,
                    BackgroundColor = bgColor
                });
            }
            rows.Add(rowCells);
        }

        // Extract border info from table properties
        var borderColor = "#000000";
        var borderWidth = 1.0;
        
        var tableProps = table.TableProperties;
        if (tableProps != null)
        {
            // Could extract more detailed border info here
        }

        return new TypstTableElement
        {
            Rows = rows,
            ColumnWidths = columnWidths,
            RowHeights = rowHeights,
            BorderColor = borderColor,
            BorderWidth = borderWidth
        };
    }

    private string ExtractCellText(Drawing.TableCell cell)
    {
        var sb = new StringBuilder();
        var textBody = cell.TextBody;
        if (textBody == null) return "";

        foreach (var paragraph in textBody.Elements<Drawing.Paragraph>())
        {
            foreach (var run in paragraph.Elements<Drawing.Run>())
            {
                if (run.Text?.Text != null)
                {
                    sb.Append(run.Text.Text);
                }
            }
        }

        return sb.ToString().Trim();
    }

    private TypstTextFormatting ExtractCellFormatting(Drawing.TableCell cell)
    {
        // Try to get formatting from first run
        var textBody = cell.TextBody;
        if (textBody == null) return new TypstTextFormatting();

        foreach (var paragraph in textBody.Elements<Drawing.Paragraph>())
        {
            foreach (var run in paragraph.Elements<Drawing.Run>())
            {
                return ExtractTextFormatting(run);
            }
        }

        return new TypstTextFormatting();
    }

    private string? ExtractCellBackground(Drawing.TableCell cell)
    {
        var cellProps = cell.TableCellProperties;
        if (cellProps == null) return null;

        var fill = cellProps.Elements<Drawing.SolidFill>().FirstOrDefault();
        if (fill != null)
        {
            return ExtractColor(fill);
        }

        return null;
    }

    private (double X, double Y, double Width, double Height) GetElementPosition(ShapeProperties? shapeProperties)
    {
        if (shapeProperties?.Transform2D == null)
            return (0, 0, 100, 50);

        var transform = shapeProperties.Transform2D;
        var x = transform.Offset?.X?.Value ?? 0;
        var y = transform.Offset?.Y?.Value ?? 0;
        var width = transform.Extents?.Cx?.Value ?? 100;
        var height = transform.Extents?.Cy?.Value ?? 50;

        return (EmuToPt((long)x), EmuToPt((long)y), EmuToPt((long)width), EmuToPt((long)height));
    }

    private (double X, double Y, double Width, double Height) GetGraphicFramePosition(P.GraphicFrame graphicFrame)
    {
        var transform = graphicFrame.Transform;
        if (transform == null)
            return (0, 0, 100, 50);

        var x = transform.Offset?.X?.Value ?? 0;
        var y = transform.Offset?.Y?.Value ?? 0;
        var width = transform.Extents?.Cx?.Value ?? 100;
        var height = transform.Extents?.Cy?.Value ?? 50;

        return (EmuToPt((long)x), EmuToPt((long)y), EmuToPt((long)width), EmuToPt((long)height));
    }

    private (uint Id, string Name) GetElementIdAndName(OpenXmlElement? nvProperties)
    {
        if (nvProperties == null) return (0, "Unknown");

        var cnvPr = nvProperties.ChildElements.FirstOrDefault(e => e.LocalName == "cNvPr");
        if (cnvPr == null) return (0, "Unknown");

        uint id = 0;
        var idAttr = cnvPr.GetAttribute("id", "");
        if (!string.IsNullOrEmpty(idAttr.Value) && uint.TryParse(idAttr.Value, out var parsedId))
        {
            id = parsedId;
        }

        var nameAttr = cnvPr.GetAttribute("name", "");
        var name = !string.IsNullOrEmpty(nameAttr.Value) ? nameAttr.Value : "Unknown";

        return (id, name);
    }

    private void ExtractFonts()
    {
        // Check if PPTX has embedded fonts
        var presentation = _document.PresentationPart!.Presentation;
        
        // Look for font parts in the presentation
        foreach (var part in _document.PresentationPart.Parts)
        {
            if (part.OpenXmlPart is FontPart fontPart)
            {
                var fileName = Path.GetFileName(fontPart.Uri.OriginalString);
                var outputPath = Path.Combine(_fontsDirectory, fileName);
                
                using (var stream = fontPart.GetStream())
                using (var fileStream = File.Create(outputPath))
                {
                    stream.CopyTo(fileStream);
                }
            }
        }

        // Also check slide parts for font references
        foreach (var slidePart in _document.PresentationPart.SlideParts)
        {
            foreach (var part in slidePart.Parts)
            {
                if (part.OpenXmlPart is FontPart fontPart)
                {
                    var fileName = Path.GetFileName(fontPart.Uri.OriginalString);
                    var outputPath = Path.Combine(_fontsDirectory, fileName);
                    
                    if (!File.Exists(outputPath))
                    {
                        using (var stream = fontPart.GetStream())
                        using (var fileStream = File.Create(outputPath))
                        {
                            stream.CopyTo(fileStream);
                        }
                    }
                }
            }
        }
    }

    private static double EmuToPt(long emu)
    {
        return emu / 12700.0;
    }

    private static string FormatPt(double pt)
    {
        return pt.ToString("F2", CultureInfo.InvariantCulture) + "pt";
    }

    private static string EscapeTypstText(string text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        
        return text
            .Replace("\\", "\\\\")
            .Replace("[", "\\[")
            .Replace("]", "\\]")
            .Replace("*", "\\*")
            .Replace("_", "\\_")
            .Replace("#", "\\#")
            .Replace("`", "\\`");
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDirectory))
            {
                Directory.Delete(_tempDirectory, true);
            }
        }
        catch
        {
            // Best effort cleanup
        }
    }
}
